module.exports = [
  {
    page_number: 31,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    subtitle: "Menyelaraskan Pabrik Kimia Tubuh Lewat Tirakat yang Membumi",
    side_a_text: "Kamu menuntut batinmu tenang, tapi ragamu kau racuni layar biru hingga fajar.",
    visual_concept: "Seseorang duduk termenung di angkringan temaram kolong jembatan Lempuyangan Yogyakarta saat senja gerimis, memandangi uap hangat yang naik perlahan dari cangkir seng loreng.",
    image_prompt: "[SUBJECT] An Indonesian man in his late 20s wearing a simple faded shirt * [ORDINARY INDONESIAN ENVIRONMENT] roadside angkringan stall beneath a concrete flyover in Yogyakarta at dusk * [HUMAN ACTION / EMOTION] sitting quietly on a wooden bench, holding a striped enamel tin cup, watching the steam rise with deep somatic presence * [ONE MEANINGFUL DETAIL] a clean continuous spiral of warm steam curling up from the tea into the cool humid twilight air * [LIGHTING] warm yellow kerosene lamp illuminating the food tray and table against the cool blue exterior twilight * [MATERIAL / TEXTURE] chipped enamel tin mug, rough bench timber, wet asphalt, damp night mist * [COMPOSITION] vertical 9:16 layout, person and cup grounded in lower half, broad calm moody atmosphere in upper half * [STYLE] atmospheric Indonesian street photography, authentic 35mm film grain, rich earth tones * [NEGATIVE CONSTRAINTS] no glowing neural circuits, no floating hormone molecules, no sci-fi cyborg overlays, no text, no watermark",
    source_anchor: "Batin yang gelisah sering kali berakar dari pabrik kimia tubuh yang kacau akibat kurang tidur, paparan cahaya biru gawai, dan ritme biologis yang dirusak.",
    reflection_target: "Pengalaman menyalahkan diri sendiri karena mudah marah atau cemas, padahal tubuh fisiknya sedang kelelahan ekstrem akibat kurang tidur."
  },
  {
    page_number: 32,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Lambung Kosong & Ketajaman Indra",
    subtitle: "Mengapa para leluhur berpuasa saat hendak mengambil keputusan besar dalam hidup.",
    side_a_text: "Saat lambungmu kosong seharian, kenapa kepalamu justru terasa lebih awas dan tajam?",
    visual_concept: "Seseorang duduk bersila di amben bambu samping sawah saat tengah hari, memandang hamparan padi yang menguning dengan tatapan jernih tanpa rasa lapar yang menyiksa.",
    image_prompt: "[SUBJECT] An Indonesian person in simple traditional cotton clothes * [ORDINARY INDONESIAN ENVIRONMENT] bamboo resting gazebo (gubuk) beside expansive rice paddies in rural Java * [HUMAN ACTION / EMOTION] sitting peacefully with hands resting on knees, eyes bright and perceptive, experiencing the deep quiet clarity of intermittent fasting * [ONE MEANINGFUL DETAIL] a single clay pitcher of water resting nearby on the bamboo floorboards * [LIGHTING] bright midday tropical sunlight softened by the thatch roof of the gazebo, gentle contrast * [MATERIAL / TEXTURE] split bamboo poles, woven thatch, golden rice stalks, weathered unpainted wood * [COMPOSITION] vertical 9:16 framing, subject centered in lower portion, open golden field and sky stretching above * [STYLE] serene landscape editorial, natural earthy color grading, fine film grain * [NEGATIVE CONSTRAINTS] no glowing stomach graphics, no digestive x-ray, no floating energy runes, no text",
    source_anchor: "Saat sistem pencernaan diistirahatkan lewat puasa, tubuh mengalihkan energi untuk perbaikan sel otak dan menajamkan radar kepekaan indrawi.",
    reflection_target: "Pengalaman merasakan kejernihan pikiran yang tak biasa ketika menjalani puasa dengan niat yang tenang dan sadar."
  },
  {
    page_number: 33,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Guyuran Air Sumur Dingin di Tengkuk",
    subtitle: "Reset instan sistem saraf simpatik lewat sentuhan air tanah alami.",
    side_a_text: "Segelas air dingin di tengkukmu saat fajar sanggup membubarkan kabut pikiran yang buntu berhari-hari.",
    visual_concept: "Seseorang membasuh tengkuk dan wajahnya dengan air timba sumur tua di pelataran belakang rumah saat fajar, butiran air berkilau di kulit.",
    image_prompt: "[SUBJECT] An Indonesian man in casual shorts leaning over a stone well * [ORDINARY INDONESIAN ENVIRONMENT] backyard well in rural Java surrounded by banana trees at early dawn * [HUMAN ACTION / EMOTION] scooping cool well water from a tin bucket and splashing it onto the back of his neck, head tilted forward, exhaling with intense somatic refreshment * [ONE MEANINGFUL DETAIL] crystalline droplets of fresh well water scattering off his neck and skin against the dark stone well ring * [LIGHTING] cool blue twilight of early dawn, gentle first light touching the wet stone and water droplets * [MATERIAL / TEXTURE] rough mossy well stones, galvanised tin bucket, wet human skin, cold well water * [COMPOSITION] vertical 9:16 layout, figure and well occupying lower two-thirds, serene dawn foliage and sky above * [STYLE] raw tactile lifestyle documentary, naturalistic exposure, rich 35mm grain * [NEGATIVE CONSTRAINTS] no glowing blue cold laser effects, no medical nervous system anatomy diagram, no text",
    source_anchor: "Membasuh tengkuk dengan air dingin merangsang saraf vagus, menurunkan detak jantung yang panik, dan mengaktifkan sistem saraf parasimpatik secara seketika.",
    reflection_target: "Momen ketika membasuh muka atau mandi air dingin di pagi hari mendadak mengembalikan kesegaran batin setelah semalaman cemas."
  },
  {
    page_number: 34,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Ritme Sirkadian & Bangun Sebelum Ayam Berkokok",
    subtitle: "Menyelaraskan detak biologis tubuh dengan perputaran poros bumi.",
    side_a_text: "Leluhurmu bangun sebelum ayam berkokok bukan karena takut terlambat kerja, melainkan menyambut gelombang fajar.",
    visual_concept: "Seseorang melangkah keluar dari pintu kayu rumah limasan saat fajar berkabut, menghirup udara segar pekarangan desa yang sunyi.",
    image_prompt: "[SUBJECT] An Indonesian person standing on the front threshold of an old limasan wooden house * [ORDINARY INDONESIAN ENVIRONMENT] rural village courtyard shrouded in light morning mist at first light * [HUMAN ACTION / EMOTION] standing upright, arms relaxed by sides, inhaling the cool mountain air with wide-open lungs and calm reverence * [ONE MEANINGFUL DETAIL] morning dew shining on the wide banana leaves in the front yard * [LIGHTING] soft lavender and amber hues of first dawn touching the horizon through coconut palms * [MATERIAL / TEXTURE] dark hand-hewn timber doorway, dewy foliage, damp gravel pathway * [COMPOSITION] vertical 9:16 frame, person framed symmetrically in the wooden doorway, tranquil morning sky rising above * [STYLE] peaceful rural visual narrative, cinematic soft contrast, fine film grain * [NEGATIVE CONSTRAINTS] no glowing clock or sun diagrams, no futuristic circadian wheels, no CGI, no text",
    source_anchor: "Bangun sebelum fajar menyinkronkan ritme hormon kortisol dan melatonin secara alami dengan siklus cahaya matahari, memulihkan energi fisik tanpa butuh kafein berlebihan.",
    reflection_target: "Pengalaman bangun pagi-pagi sekali saat udara masih sangat segar dan merasakan betapa tenangnya dunia sebelum kebisingan dimulai."
  },
  {
    page_number: 35,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Napas Diafragma & Menenangkan Alarm Bahaya",
    subtitle: "Mengembalikan napas pendek yang panik ke dasar perut yang kokoh.",
    side_a_text: "Napasmu pendek dan memburu di dada; pantas saja hidupmu terasa seperti dikejar bahaya setiap hari.",
    visual_concept: "Seseorang duduk bersila santai di atas tikar pandan di teras rumah, meletakkan satu telapak tangan di atas pusar sembari menarik napas dalam yang mengembang perlahan.",
    image_prompt: "[SUBJECT] An Indonesian person sitting in relaxed cross-legged posture on a woven pandan mat * [ORDINARY INDONESIAN ENVIRONMENT] breezy shaded veranda of a village home in the afternoon * [HUMAN ACTION / EMOTION] one hand resting gently over the lower abdomen just below the navel, shoulders dropped and relaxed, breathing deeply into the belly * [ONE MEANINGFUL DETAIL] the gentle rise of the cotton shirt over the abdomen indicating a deep, centered diaphragmatic breath * [LIGHTING] soft warm afternoon side light passing through potted ferns * [MATERIAL / TEXTURE] woven pandanus mat, smooth unpainted floorboards, soft textured cotton clothing * [COMPOSITION] vertical 9:16 composition, figure grounded in lower half, peaceful open porch background with clean space above * [STYLE] mindful lifestyle photography, calming earthy palette, delicate analog grain * [NEGATIVE CONSTRAINTS] no glowing blue lungs, no medical arrows showing air flow, no CGI ribs, no text",
    source_anchor: "Napas pendek di dada mengirim sinyal ke amigdala bahwa kamu sedang dalam ancaman bahaya. Memindahkan napas ke dasar diafragma mematikan sinyal bahaya palsu itu.",
    reflection_target: "Pengalaman menyadari bahwa saat merasa tertekan atau panik, tarikan napas tanpa sadar menjadi sangat pendek dan dangkal di dada."
  },
  {
    page_number: 36,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Misteri Sentong Tengah & Tirakat Malam",
    subtitle: "Kamar paling gelap di dalam rumah tempat raga melepaskan seluruh beban visual.",
    side_a_text: "Di ruangan mana di rumahmu kamu sanggup duduk tanpa cahaya selain degup napasmu sendiri?",
    visual_concept: "Seseorang duduk bersila di atas amben sentong tengah rumah limasan kayu jati kuno dalam kegelapan pekat yang menenangkan.",
    image_prompt: "[SUBJECT] Silhouette of an Indonesian person seated calmly in the center of an ancient room * [ORDINARY INDONESIAN ENVIRONMENT] traditional Javanese inner private chamber (sentong tengah) enveloped in deep gloom * [HUMAN ACTION / EMOTION] sitting in still meditative repose, comfortable in absolute silence and visual sensory deprivation * [ONE MEANINGFUL DETAIL] a sliver of faint ambient light escaping under a heavy carved teak door, barely outlining the floor * [LIGHTING] extreme low-key lighting, rich natural deep charcoal shadows with soft edge definition * [MATERIAL / TEXTURE] ancient polished teak panels, woven mat, darkness as a tactile physical medium * [COMPOSITION] vertical 9:16 portrait frame, centered silhouette in lower frame surrounded by vast quiet shadow * [STYLE] minimalist chiaroscuro fine art photography, atmospheric grain, deep velvet blacks * [NEGATIVE CONSTRAINTS] no glowing third eye, no spooky horror effects, no purple fantasy aura, no text",
    source_anchor: "Sentong tengah adalah ruangan tanpa jendela di inti rumah Jawa, dirancang untuk memberi kegelapan mutlak agar kelenjar pineal beristirahat total dan membuka penglihatan batin.",
    reflection_target: "Pengalaman duduk sejenak di kamar yang benar-benar gelap dan merasakan betapa lelahnya mata dan otak kita selama ini terpapar cahaya buatan."
  },
  {
    page_number: 37,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Mencicipi Pahit Sebelum Ditagih Semesta",
    subtitle: "Laku prihatin sukarela selagi sehat demi menggembleng ketangguhan fisik dan saraf.",
    side_a_text: "Bayarlah kepahitan di depan selagi ragamu kuat, jangan tunggu semesta menagihnya dengan paksa.",
    visual_concept: "Seseorang membasuh wajah dan tengkuknya dengan air dingin dari gayung tempurung kelapa di samping sumur batu pekarangan desa saat sepertiga malam sebelum fajar, butiran air berkilau di kulit dalam udara fajar yang dingin menyegarkan.",
    image_prompt: "[SUBJECT] An Indonesian man in simple shorts leaning beside a traditional stone water well * [ORDINARY INDONESIAN ENVIRONMENT] quiet open-air backyard of a Javanese village home in the cold pre-dawn third of the night * [HUMAN ACTION / EMOTION] washing his face and the back of his neck with fresh icy-cold well water scooped with a natural coconut shell dipper (siwur) * [ONE MEANINGFUL DETAIL] glistening cold water droplets clinging to his skin, subtle mist of his warm breath visible in the chilled pre-dawn air * [LIGHTING] deep indigo twilight with a single warm lantern on the well rim casting sharp reflective glints on wet stone * [MATERIAL / TEXTURE] rough river rock well, polished coconut shell, wet skin, damp gravel ground * [COMPOSITION] vertical 9:16 layout, person bending over the well in lower frame, calm quiet night sky above * [STYLE] atmospheric Indonesian documentary cinema, earthy cold-and-warm color balance, tactile 35mm grain * [NEGATIVE CONSTRAINTS] no glowing aura, no fantasy mist, no supernatural spirits, no CGI, no text, no watermark",
    source_anchor: "Bayarlah kepahitan di depan selagi kamu masih sehat dan kuat... sengajalah berpuasa saat makanan melimpah, sengajalah mandi air dingin di pagi buta.",
    reflection_target: "Pengalaman merasakan kesegaran dan ketangguhan batin yang luar biasa setelah dengan sengaja menantang diri mandi air dingin atau berpuasa saat keadaan lapang."
  },
  {
    page_number: 38,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Tiga Benteng Pertahanan Purba Manusia",
    subtitle: "Tiga kelenjar terbawah raga sebagai tungku api pertahanan dan kedaulatan biologis.",
    side_a_text: "Tiga kelenjar bawahmu adalah tungku api raga; jika energimu terkunci di sana, hidupmu habis diperbudak cemas.",
    visual_concept: "Seorang pandai besi tradisional Jawa (empu) di dekat perapian tungku bara arang yang menyala merah membara di lantai bengkel tempa, memegang tang besi dengan tumpuan panggul dan pinggang yang kokoh berakar ke bumi.",
    image_prompt: "[SUBJECT] A focused, muscular middle-aged Javanese traditional blacksmith (empu) in dark apron and rolled pants * [ORDINARY INDONESIAN ENVIRONMENT] rustic open-sided earthen forge workshop * [HUMAN ACTION / EMOTION] standing in a grounded, powerful half-crouch with pelvis and lower spine solidly rooted to the dirt floor, holding forging tongs near glowing hearth coals * [ONE MEANINGFUL DETAIL] rich crimson and ember-orange glow from the charcoal furnace illuminating his lower core and waist, visually anchoring the base energy * [LIGHTING] intense warm charcoal embers from ground level cutting through atmospheric shadows of the soot-stained workshop * [MATERIAL / TEXTURE] raw black anvil, glowing embers, cracked clay furnace, coarse cotton apron, textured skin * [COMPOSITION] vertical 9:16 framing, glowing hearth and rooted blacksmith occupying lower half, quiet smoky rafters overhead * [STYLE] visceral artisan documentary photography, rich deep chiaroscuro, natural cinematic grain * [NEGATIVE CONSTRAINTS] no floating chakra wheels, no cartoon fire, no magical sparks, no CGI graphics, no text",
    source_anchor: "Tiga kelenjar bawah ini adalah tungku api pertahanan raga... gonad kelenjar reproduksi, pankreas pengatur gula darah, adrenal komandan keberanian.",
    reflection_target: "Pengalaman merasakan ketegangan dan kekakuan di area panggul dan perut bawah saat dirundung kekhawatiran materi atau ancaman finansial."
  },
  {
    page_number: 39,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Empat Menara Cahaya Menuju Langit Batin",
    subtitle: "Ketika energi hidup mendaki menuju keheningan dada, tenggorokan, dan puncak kepala.",
    side_a_text: "Saat empat menara atasmu menyala, kamu memandang sesama dengan welas asih, bukan lagi sekadar memburu makan.",
    visual_concept: "Seseorang duduk hening di teras pendopo kayu menatap empat lentera minyak gantung berjajar vertikal yang menyala lembut dari bawah ke atas dalam temaram malam, postur dada terbuka dan leher tegak rileks.",
    image_prompt: "[SUBJECT] An Indonesian contemplative seated in effortless upright posture on dark teak floorboards * [ORDINARY INDONESIAN ENVIRONMENT] open wooden veranda of a traditional Javanese joglo house at night * [HUMAN ACTION / EMOTION] sitting peacefully with chest gently open and throat upright, looking quietly toward four vertical hanging oil lamps arranged in an ascending row * [ONE MEANINGFUL DETAIL] four modest traditional brass oil lamps (lampu teplok) suspended at distinct vertical heights, their soft warm golden flames ascending cleanly * [LIGHTING] soft ambient amber glow from the real oil lamps casting warm accents on the figure's chest, neck, and brow * [MATERIAL / TEXTURE] aged teak posts, hand-woven cotton attire, delicate warm glass chimneys, deep night air * [COMPOSITION] vertical 9:16 composition, serene figure in lower third, the vertical alignment of four warm lantern lights rising through the frame * [STYLE] poetic fine-art realism, intimate meditative lighting, authentic analog film grain * [NEGATIVE CONSTRAINTS] no rainbow chakra beams, no magical glowing spheres, no fantasy temple, no CGI graphics, no text",
    source_anchor: "Dari tungku bawah, energi hidup mendaki melintasi empat menara cahaya: timus di dada, tiroid di leher, pineal di tengah kepala, dan pituitari di ubun-ubun.",
    reflection_target: "Pengalaman merasakan kelegaan dan kejernihan batin yang luas ketika mampu menanggalkan ego hewani dan memandang masalah dengan ketulusan dada."
  },
  {
    page_number: 40,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Bharatayuddha yang Berkecamuk di Balik Batok Kepala",
    subtitle: "Perang abadi antara amigdala yang cemas dan kesadaran murni penuntun hidup.",
    side_a_text: "Perang Bharatayuddha bukan dongeng kuno di Astina; ia berkecamuk di balik batok kepalamu setiap hari.",
    visual_concept: "Di balik kelir putih pertunjukan wayang malam hari, dua wayang kulit purwa (tokoh Sri Kresna bermahkota tenang berhadapan dengan tokoh Sengkuni yang licik) terpancang di gedebog pisang dalam sorot temaram lampu blencong.",
    image_prompt: "[SUBJECT] Two authentic Javanese leather shadow puppets (wayang kulit) planted firmly in a fresh banana trunk base (gedebog) * [ORDINARY INDONESIAN ENVIRONMENT] behind the taut white cotton screen (kelir) in an open pendopo at night * [HUMAN ACTION / EMOTION] the calm, poised figure of Sri Kresna facing the crooked, agitated profile of Sengkuni in a tense, silent dramatic confrontation * [ONE MEANINGFUL DETAIL] warm flickering flame of the hanging brass oil lamp (blencong) casting sharp, intricate perforated leather shadows onto the cotton screen * [LIGHTING] low warm golden tungsten and oil flame lighting contrasting rich velvety shadows * [MATERIAL / TEXTURE] perforated water-buffalo leather, gilded pigments, damp green banana trunk, woven cotton screen * [COMPOSITION] vertical 9:16 framing, puppets and banana trunk anchored in lower-mid frame, dynamic shadow patterns rising onto screen above * [STYLE] high-contrast dramatic cultural cinema still, rich natural sepia and bronze tones, tactile 35mm grain * [NEGATIVE CONSTRAINTS] no modern cartoon colors, no glowing neon auras, no sci-fi battle lasers, no CGI, no text",
    source_anchor: "Kisah Bharatayuddha di pewayangan sesungguhnya peta saraf kepalamu: Sengkuni si amigdala cemas berhadapan dengan Sri Kresna si kesadaran pineal dan Arjuna prefrontal cortex.",
    reflection_target: "Pengalaman mengamati pergulatan batin saat pikiran licik dan ketakutan masa depan mencoba memicu kepanikan, sementara hati kecil mengajak untuk tetap tenang dan jujur."
  },
  {
    page_number: 41,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Ganesha di Balik Leher dan Kera Liar Sun Go Kong",
    subtitle: "Mengunci keliaran pikiran dengan cincin kesadaran sebelum merusak hidupmu.",
    side_a_text: "Pikiranmu adalah kera liar yang lincah; tanpa cincin kesadaran di kepala, ia akan mengacak-acak hidupmu.",
    visual_concept: "Sebuah arca batu Ganesha kuno berlumut bersanding dengan ukiran relief kayu kera bijak di sudut pelataran batu candi Jawa, disinari seberkas cahaya fajar tipis yang mistis.",
    image_prompt: "[SUBJECT] A weathered ancient stone Ganesha statue alongside a traditional weathered Javanese teak wood relief depicting a contemplative monkey * [ORDINARY INDONESIAN ENVIRONMENT] quiet mossy stone courtyard of an old heritage sanctuary at dawn * [HUMAN ACTION / EMOTION] still, timeless stone presence embodying physical equilibrium and the disciplined mind * [ONE MEANINGFUL DETAIL] soft green damp moss and tiny wild ferns growing organically on the carved volcanic andesite stone * [LIGHTING] single shaft of gentle cool dawn sunlight piercing through tree canopies, illuminating the carvings * [MATERIAL / TEXTURE] porous andesite stone, dark weathered teak grain, velvety green moss, cool morning moisture * [COMPOSITION] vertical 9:16 layout, stone sculpture grounded in lower half, lush leafy vertical background rising above * [STYLE] timeless architectural and cultural documentary photography, muted earthy slate and verdant tones, 35mm grain * [NEGATIVE CONSTRAINTS] no glowing third eye, no cartoon monkey characters, no neon energy halos, no fantasy CGI, no text",
    source_anchor: "Sosok Dewa Ganesha mencerminkan otak kecil pengatur keseimbangan raga, sedangkan Kera Sakti Sun Go Kong memotret keliaran pikiran yang harus dikunci cincin penjinak kesadaran.",
    reflection_target: "Pengalaman menyadari bagaimana pikiran sering kali meloncat-loncat liar dari satu kecemasan ke kecemasan lain persis seperti kera di atas dahan."
  },
  {
    page_number: 42,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Ritme Tiga Puluh Lima Hari Pembaruan Diri",
    subtitle: "Pembaruan cairan hayat raga dalam siklus selapanan dan tirakat apit weton.",
    side_a_text: "Tiga puluh lima hari sekali ragamu memperbarui cairannya; selaraskan hidupmu dengan ritme alami semesta.",
    visual_concept: "Sebuah kalender penanggalan Jawa kuno (Pranata Mangsa & Wuku) berbahan kayu ukir bersanding dengan mangkuk air bunga setaman di atas meja kayu jati saat fajar.",
    image_prompt: "[SUBJECT] An authentic carved wooden Javanese calendar tablet (Pranata Mangsa / Wuku board) beside a small clay bowl of fresh water with floating jasmine petals * [ORDINARY INDONESIAN ENVIRONMENT] quiet corner of an old Javanese limasan wooden interior in the early morning * [HUMAN ACTION / EMOTION] quiet contemplative cultural presence of ancient biological timekeeping * [ONE MEANINGFUL DETAIL] crisp Javanese numerical and astral carvings incised into the weathered dark teak tablet, a single fresh white jasmine petal floating in the clear bowl * [LIGHTING] soft golden side-light raking across the carved wood reliefs from an open doorway * [MATERIAL / TEXTURE] aged carved teakwood, porous terracotta bowl, delicate translucent jasmine petals, cool morning dust motes * [COMPOSITION] vertical 9:16 close-up framing, calendar tablet and floral bowl centered in lower half, peaceful dark wood wall space above * [STYLE] elegant cultural heritage still-life photography, rich natural warm wood tones, tactile film grain * [NEGATIVE CONSTRAINTS] no glowing calendar numbers, no floating astrological symbols, no sci-fi holograms, no text, no watermark",
    source_anchor: "Setiap tiga puluh lima hari sekali, komposisi cairan serebrospinal di tulang punggungmu mencapai puncak kristalisasi alaminya... kalender selapanan dan puasa apit weton.",
    reflection_target: "Pengalaman memperhatikan bagaimana kondisi stamina fisik dan emosi batin berputar dalam ritme siklus bulanan tertentu yang berulang secara berkala."
  },
  {
    page_number: 43,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Sains Pembersih Residu di Sekitarmu",
    subtitle: "Mineral garam laut krosok dan daun kelor pembersih racun ionik dan logam berat.",
    side_a_text: "Garam krosok dan daun kelor bukan takhayul; mereka mineral bumi yang membasuh muatan listrik berlebih di kulitmu.",
    visual_concept: "Toples kaca bening berisi butiran kristal garam krosok laut kasar dan seikat daun kelor hijau segar di atas tampah bambu di samping gentong air tanah liat di dapur pawon Jawa.",
    image_prompt: "[SUBJECT] An honest still-life of traditional Javanese natural cleansing elements: a simple clear glass jar filled with coarse natural sea salt crystals (garam krosok) alongside fresh bundles of green moringa leaves (daun kelor) * [ORDINARY INDONESIAN ENVIRONMENT] rustic corner of an open Javanese pawon kitchen beside a traditional clay water cistern (gentong) * [HUMAN ACTION / EMOTION] tangible connection to natural grounding minerals and ancient physical cleansing science * [ONE MEANINGFUL DETAIL] translucent, coarse cubic sea salt crystals catching ambient daylight next to dew-kissed delicate round moringa leaflets * [LIGHTING] gentle natural morning light coming through wooden window slats, highlighting salt facets and leaf textures * [MATERIAL / TEXTURE] rough hand-woven bamboo winnowing tray (tampah), coarse sea salt, fresh moringa greenery, unglazed clay cistern * [COMPOSITION] vertical 9:16 layout, salt jar and moringa arranged in lower frame, tranquil rustic earthen kitchen backdrop rising above * [STYLE] earthy organic documentary photography, natural palette, tactile 35mm grain * [NEGATIVE CONSTRAINTS] no magical glowing green aura, no flying chemical ion symbols, no hospital sanitizers, no text",
    source_anchor: "Garam krosok kasar itu kristal halit alami yang sarat ion negatif... daun kelor kaya antioksidan pembersih racun logam berat.",
    reflection_target: "Pengalaman merasakan tubuh menjadi jauh lebih ringan dan segar setelah mandi air hangat bercampur garam alami sehabis seharian terpapar gawai dan keramaian kota."
  },
  {
    page_number: 44,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Menarik Rem Darurat Tubuh Lewat Napas Panjang",
    subtitle: "Kaidah napas parasimpatis empat-empat-delapan untuk mematikan alarm kepanikan di kepala.",
    side_a_text: "Tarik empat, tahan empat, hembus delapan; kendalikan napasmu sebelum kepanikan mengendalikan hidupmu.",
    visual_concept: "Seseorang duduk hening di teras rumah kayu, mata terpejam tenang, kedua telapak tangan menangkup di atas pusar yang rileks, hembusan napas halus mengalir dari celah bibir.",
    image_prompt: "[SUBJECT] An Indonesian man in relaxed linen clothing seated comfortably on a low wooden bench * [ORDINARY INDONESIAN ENVIRONMENT] peaceful open veranda of a rural home facing a lush garden in the cool late afternoon * [HUMAN ACTION / EMOTION] sitting in completely centered stillness, eyes softly closed, both palms resting gently over his lower abdomen, exhaling smoothly and slowly through relaxed parted lips * [ONE MEANINGFUL DETAIL] the completely relaxed shoulders and dropped jaw reflecting total parasympathetic nervous system release * [LIGHTING] soft golden hour ambient sunlight filtering through tropical foliage, casting long gentle shadows * [MATERIAL / TEXTURE] natural woven linen, smooth wooden bench, textured garden leaves, calm atmosphere * [COMPOSITION] vertical 9:16 framing, subject centered in lower half, expansive serene garden greenery filling the upper frame * [STYLE] tranquil mindful lifestyle photography, muted warm earthy palette, delicate film grain * [NEGATIVE CONSTRAINTS] no glowing lung diagrams, no animated breath arrows, no floating medical numbers, no CGI, no text",
    source_anchor: "Pakai kaidah napas parasimpatis empat-empat-delapan... rasio hembusan dua kali lebih panjang dari tarikan adalah sinyal biologis mutlak buat menarik rem darurat jantung.",
    reflection_target: "Pengalaman merasakan detak jantung yang berdebar kencang mendadak melambat tenang hanya dengan beberapa kali menghembuskan napas panjang dan perlahan."
  },
  {
    page_number: 45,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Menjadi Tuan di Rumah Diri Sendiri",
    subtitle: "Kedaulatan sejati dimulai saat kamu mampu mengendalikan apa yang masuk dan keluar dari ragamu.",
    side_a_text: "Kuasai ragamu maka kau menguasai takdirmu; jadilah tuan yang berdaulat di rumahmu sendiri.",
    visual_concept: "Seseorang berdiri tegak dan tenang dengan kaki telanjang menjejak pasir vulkanik lereng Gunung Merapi saat pagi benderang, angin gunung menerpa bajunya.",
    image_prompt: "[SUBJECT] An Indonesian person in simple traditional linen clothes standing tall, grounded, and centered * [ORDINARY INDONESIAN ENVIRONMENT] volcanic landscape on the slopes of Mount Merapi in clear early morning * [HUMAN ACTION / EMOTION] standing upright with hands relaxed at sides, barefoot on volcanic soil, gazing at the distant misty horizon with quiet self-mastery * [ONE MEANINGFUL DETAIL] fresh hardy green wild grass sprouting tenaciously from the dark fertile volcanic ash around their feet * [LIGHTING] clear, crisp high-altitude morning sunlight, clean sharp shadows * [MATERIAL / TEXTURE] dark volcanic sand, weathered stone, coarse unbleached linen, cool mountain air * [COMPOSITION] vertical 9:16 layout, person standing firmly in lower half, majestic open mountain sky rising above * [STYLE] epic yet restrained documentary photography, crisp organic detail, 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing superhero energy shields, no divine light beams, no mythical beings in clouds, no CGI, no text",
    source_anchor: "Siapa yang tidak mampu mengendalikan apa yang ia suapkan ke mulutnya, berapa jam ia tidur, dan bagaimana ia bernapas, ia tidak akan pernah mampu menjadi pemimpin atas nasib hidupnya.",
    reflection_target: "Momen ketika berhasil menata ulang pola tidur, makanan, dan kebiasaan harian, lalu merasakan kendali hidup kembali berada di tangan sendiri."
  }
];
