module.exports = [
  {
    page_number: 60,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Menjadi Manusia Normal & Seni Berserah",
    subtitle: "Menanggalkan Jubah Kesucian Palsu, Hubungan Sakral, dan Pasrah Sumarah",
    side_a_text: "Kamu mengira puncak ilmu batin membuatmu kebal, padahal esensinya adalah kembali menjadi manusia biasa.",
    visual_concept: "Seseorang menanggalkan sandal jepit di teras semen depan, melangkah masuk dengan kaki telanjang ke ruang makan keluarga yang hangat di mana piring makan malam mulai ditata.",
    image_prompt: "[SUBJECT] An Indonesian father stepping barefoot from the entrance threshold * [ORDINARY INDONESIAN ENVIRONMENT] entrance of a modest, warm Indonesian home in early evening * [HUMAN ACTION / EMOTION] taking off worn rubber sandals at the porch, stepping onto cool patterned cement floor with a deep sense of relief and grounded normality * [ONE MEANINGFUL DETAIL] neatly placed rubber sandals resting on the cool porch step, doorway opening into a softly lit dining area * [LIGHTING] warm amber incandescent house light spilling out into the twilight porch * [MATERIAL / TEXTURE] cool patterned vintage cement tiles, worn rubber sandals, dark timber doorframe * [COMPOSITION] vertical 9:16 framing, subject entering lower-mid frame, warm welcoming home interior above * [STYLE] poignant domestic realism, intimate authentic atmosphere, fine 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing holy robes, no floating aura, no superhero cape, no text, no watermark",
    source_anchor: "Puncak tertinggi dari seluruh laku spiritual bukanlah kemampuan terbang atau kebal senjata, melainkan kesanggupan menjadi manusia normal: bekerja jujur, menyayangi keluarga, dan tahu kapan harus berserah.",
    reflection_target: "Pengalaman menyadari bahwa kedamaian sejati bukan ada pada klaim kesucian atau ilmu tinggi, melainkan pada ketulusan menjalani peran sehari-hari di rumah."
  },
  {
    page_number: 61,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Ketika Kesucian Berubah Menjadi Topeng Baru",
    subtitle: "Spiritual bypass: jebakan ego halus yang merasa lebih suci daripada orang lain.",
    side_a_text: "Kenapa setelah belajar meditasi, kamu malah jadi lebih gampang menghakimi isi piring orang lain?",
    visual_concept: "Sebuah topeng kayu antik tergeletak di atas meja warung tenda pecel lele pinggir jalan di samping gelas teh manis hangat, sementara orang-orang makan dengan santai di sekitarnya.",
    image_prompt: "[SUBJECT] A simple carved wooden mask resting on a plastic-covered table * [ORDINARY INDONESIAN ENVIRONMENT] roadside night food tent (warung tenda pecel lele) in an Indonesian city * [HUMAN ACTION / EMOTION] no direct face visible, focus on the object in everyday bustling life; quiet irony of spiritual pretensions meeting raw street reality * [ONE MEANINGFUL DETAIL] an ordinary glass mug of hot sweet tea with a yellow plastic spoon resting beside the traditional wooden mask * [LIGHTING] bright warm yellow fluorescent tube hanging inside the cloth tent, casting honest street shadows * [MATERIAL / TEXTURE] carved wood patina, colorful plastic table covering, condensation on glass mug * [COMPOSITION] vertical 9:16 layout, table and mask in lower half, striped canvas tent and street backdrop above * [STYLE] candid Indonesian street photography, rich color saturation, authentic 35mm grain * [NEGATIVE CONSTRAINTS] no floating demonic egos, no glowing third eye, no mystical fog, no text",
    source_anchor: "Ego spiritual adalah bentuk kesombongan yang paling licik. Begitu kamu merasa lebih bersih dan suci dibanding orang awam yang makan di warung pinggir jalan, kamu baru saja mengenakan topeng baru.",
    reflection_target: "Pengalaman menyadari saat diri sendiri mendadak merasa lebih paham atau lebih suci dibanding teman atau keluarga hanya karena baru mempelajari ilmu batin."
  },
  {
    page_number: 62,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Menatap Mata Tukang Sayur Tanpa Rasa Lebih Tinggi",
    subtitle: "Ujian kesadaran yang sesungguhnya terjadi di pasar becek, bukan di puncak gunung sunyi.",
    side_a_text: "Puncak pencarian batinmu bukan menjadi malaikat, melainkan sanggup menatap mata tukang sayur tanpa rasa lebih tinggi.",
    visual_concept: "Percakapan bersahaja di samping gerobak sayur keliling saat fajar, uang kertas lecek berpindah tangan dengan senyum tulus dan tatapan mata yang sejajar.",
    image_prompt: "[SUBJECT] An Indonesian person buying vegetables from an elderly itinerant vendor * [ORDINARY INDONESIAN ENVIRONMENT] quiet village lane in early morning mist beside a wooden vegetable pushcart * [HUMAN ACTION / EMOTION] exchanging crumpled paper rupiah banknotes and fresh leafy greens with genuine eye-to-eye warmth and humility * [ONE MEANINGFUL DETAIL] a bunch of fresh green water spinach and a packet of tofu resting on top of the wooden pushcart * [LIGHTING] soft golden early morning daylight filtering through roadside banana leaves * [MATERIAL / TEXTURE] worn paper currency, fresh dewy vegetables, weathered timber cart, cotton morning clothes * [COMPOSITION] vertical 9:16 framing, hands and vegetable exchange in mid-ground, village road receding into morning light above * [STYLE] warm humanistic documentary photography, rich earth colors, tactile film grain * [NEGATIVE CONSTRAINTS] no halo of charity, no glowing divine light, no melodramatic poverty pornography, no text",
    source_anchor: "Bila kamu sanggup memandang setiap orang awam dengan rasa hormat yang setara layaknya memandang gurumu sendiri, di situlah kesadaran manunggal benar-benar hidup.",
    reflection_target: "Pengalaman berinteraksi secara tulus dan menghargai orang-orang sederhana yang melayani kebutuhan hidup kita setiap hari tanpa rasa merendahkan."
  },
  {
    page_number: 63,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Sakralitas Hubungan Suami Istri & Pertukaran Energi",
    subtitle: "Penyatuan dua jiwa di balik kelambu kamar tidur sebagai kuil pertukaran medan takdir.",
    side_a_text: "Pernahkah kamu menyadari, di balik kelambu tidurmu, dua jiwa sedang saling menukar cetak biru nasibnya?",
    visual_concept: "Kelambu katun tipis di kamar tidur rumah limasan pedesaan saat temaram petang, sepasang sandal tidur berjajar rapi di lantai kayu samping ranjang.",
    image_prompt: "[SUBJECT] An intimate, quiet bedroom interior in an old Indonesian wooden home * [ORDINARY INDONESIAN ENVIRONMENT] modest rural bedroom with antique timber walls at dusk * [HUMAN ACTION / EMOTION] quiet sanctuary of domestic intimacy; two pairs of fabric slippers neatly side-by-side on the wooden floorboards * [ONE MEANINGFUL DETAIL] a sheer white cotton mosquito net (kelambu) draped gently around the dark wood bed frame, catching the soft twilight * [LIGHTING] gentle warm amber glow from a single dim bedside lamp, soft deep shadows in the room corners * [MATERIAL / TEXTURE] sheer cotton mesh, dark aged teak floorboards, handwoven bedside rug, cool evening air * [COMPOSITION] vertical 9:16 layout, slippers and floor in lower third, graceful drape of the bed canopy rising above * [STYLE] poetic fine art interior photography, muted warm palette, soft romantic grain * [NEGATIVE CONSTRAINTS] no explicit erotic graphics, no glowing tantric energy coils, no fantasy deities in bedroom, no text",
    source_anchor: "Penyatuan biologis dan batin antara suami-istri adalah ritual sakral pertukaran cetak biru energi. Di sanalah dua arus karma melebur dan membentuk wadah bagi generasi berikutnya.",
    reflection_target: "Pengalaman merasakan kedalaman ikatan batin dengan pasangan hidup yang jauh melampaui sekadar ketertarikan fisik sesaat."
  },
  {
    page_number: 64,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Jejak Luka Masa Lalu di Tubuh Pasangan",
    subtitle: "Menerima pasangan bukan cuma menerima keindahannya, tapi memeluk seluruh riwayat kerapuhannya.",
    side_a_text: "Saat menyentuh pasanganmu, kamu tidak cuma menyentuh kulitnya, melainkan seluruh riwayat luka yang ia bawa sejak kecil.",
    visual_concept: "Dua cangkir teh hangat di meja teras sore hari, sepasang tangan bersahaja yang saling menggenggam lembut di atas meja kayu lapuk tanpa kata-kata.",
    image_prompt: "[SUBJECT] Two hands gently resting together on a wooden tabletop * [ORDINARY INDONESIAN ENVIRONMENT] quiet outdoor wooden veranda overlooking a leafy garden in the late afternoon * [HUMAN ACTION / EMOTION] one weathered hand tenderly holding another's hand with silent, unconditional acceptance and understanding * [ONE MEANINGFUL DETAIL] two simple ceramic mugs of warm jasmine tea resting nearby on the table, steam gently rising * [LIGHTING] soft golden afternoon light skimming across the texture of the skin and wood * [MATERIAL / TEXTURE] textured skin with natural veins, rough weathered teak tabletop, warm glazed ceramic * [COMPOSITION] vertical 9:16 intimate close-up framing, hands centered in lower-mid frame, peaceful garden blur above * [STYLE] emotionally resonant documentary photography, natural warm tones, analog 35mm grain * [NEGATIVE CONSTRAINTS] no glowing aura around hands, no comic book energy cords, no melodramatic fantasy tears, no text",
    source_anchor: "Mencintai seseorang secara dewasa berarti bersedia menjadi ruang aman bagi luka-luka batin masa lalunya yang belum sembuh, tanpa berusaha menuntutnya menjadi sempurna.",
    reflection_target: "Pengalaman memahami mengapa pasangan memiliki ketakutan atau sensitivitas tertentu, lalu memilih untuk merangkulnya dengan sabar daripada memarahinya."
  },
  {
    page_number: 65,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Menyerah Itu Marah, Berserah Itu Tuntas",
    subtitle: "Perbedaan mendasar antara keputusasaan yang melarikan diri dan kepasrahan yang telah menuntaskan ikhtiar.",
    side_a_text: "Menyerah itu saat kamu melempar dayung karena marah; berserah adalah melepas kemudi setelah seluruh dayungmu tuntas.",
    visual_concept: "Seorang nelayan Pantai Selatan duduk di atas perahu kayu yang bersandar di pasir pantai basah saat senja, membiarkan buih ombak menyapu kakinya setelah melaut semalaman.",
    image_prompt: "[SUBJECT] An Indonesian fisherman in simple shorts and faded shirt resting on his outrigger boat * [ORDINARY INDONESIAN ENVIRONMENT] black sand beach on the southern coast of Java at sunset * [HUMAN ACTION / EMOTION] sitting relaxed on the wooden outrigger, gaze resting on the vast ocean horizon with profound, settled peace * [ONE MEANINGFUL DETAIL] sea foam from a spent wave gently washing over his bare feet on the wet dark sand * [LIGHTING] dramatic golden and violet sunset light reflecting off the wet sand and breaking waves * [MATERIAL / TEXTURE] weathered painted timber of the boat, wet volcanic black sand, sea foam bubbles, salty air * [COMPOSITION] vertical 9:16 landscape portrait, fisherman and boat grounded in lower half, immense ocean and radiant dusk sky above * [STYLE] epic naturalistic maritime photography, deep rich contrast, crisp 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing divine hands from clouds, no cartoon stormy waves, no fantasy angels, no text",
    source_anchor: "Pasrah sumarah bukan sikap malas orang yang enggan berjuang. Ia adalah penyerahan total hasil akhir kepada Sang Dalang setelah seluruh daya raga dikerahkan maksimal.",
    reflection_target: "Momen ketika setelah berjuang sekuat tenaga menghadapi ujian berat, kita akhirnya bisa menarik napas lega dan menyerahkan hasil akhirnya kepada Tuhan."
  },
  {
    page_number: 66,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Seni Melepas Kemudi Takdir",
    subtitle: "Belajar mempercayai bahwa arus sungai kehidupan tahu persis ke mana ia membawamu.",
    side_a_text: "Ada kelegaan luar biasa saat kamu akhirnya mengakui bahwa hidup ini bukan panggung yang bisa kau atur sendiri.",
    visual_concept: "Sehelai daun jati kering yang jatuh melayang perlahan dan mendarat di permukaan air parit desa yang mengalir tenang tanpa perlawanan.",
    image_prompt: "[SUBJECT] A solitary dry teak leaf (daun jati) floating on clear moving stream water * [ORDINARY INDONESIAN ENVIRONMENT] shallow stone-lined irrigation channel in rural Java * [HUMAN ACTION / EMOTION] no human visible, but meditative human viewpoint; feeling of effortless surrender to life's current * [ONE MEANINGFUL DETAIL] the textured dry brown leaf floating naturally on the surface, casting a soft shadow on the pebbled stream bed beneath * [LIGHTING] dappled midday sunlight filtering through bamboo leaves onto the water * [MATERIAL / TEXTURE] crisp dry leaf veins, clear rippling stream water, smooth river stones beneath * [COMPOSITION] vertical 9:16 layout, floating leaf in lower frame, tranquil flowing water stretching into soft focus above * [STYLE] poetic Zen-like nature photography, organic green and brown palette, fine film grain * [NEGATIVE CONSTRAINTS] no glowing golden leaves, no magical whirlpools, no fantasy fairy dust, no text",
    source_anchor: "Kelelahan batin terbesarmu berasal dari nafsu ingin mengatur jalannya takdir. Saat kamu belajar mengalir seperti daun di atas air, beban di pundakmu seketika luruh.",
    reflection_target: "Pengalaman merasa sangat lelah karena berusaha memaksakan sebuah rencana yang terus gagal, lalu merasa damai saat membiarkan segalanya mengalir apa adanya."
  },
  {
    page_number: 67,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Jebakan Ingin Menjadi Penyelamat",
    subtitle: "Ketika niat menolong orang lain diam-diam ditunggangi oleh kebutuhan ego untuk merasa berjasa.",
    side_a_text: "Apakah kamu benar-benar ingin menolongnya, atau cuma haus merasa dibutuhkan sebagai pahlawan dalam hidup orang lain?",
    visual_concept: "Seseorang berdiri di samping jendela rumah, menahan diri untuk tidak mencampuri urusan tetangga yang sedang menyelesaikan masalah keluarganya sendiri.",
    image_prompt: "[SUBJECT] An Indonesian person standing indoors beside a wooden window with slatted shutters * [ORDINARY INDONESIAN ENVIRONMENT] quiet home interior during the quiet heat of the afternoon * [HUMAN ACTION / EMOTION] looking out with thoughtful restraint, one hand resting on the window frame, consciously choosing non-interference and respectful space * [ONE MEANINGFUL DETAIL] half-open wooden shutters creating bars of shadow and light across their chest * [LIGHTING] bright tropical exterior daylight contrasted with the cool, dim interior shadows * [MATERIAL / TEXTURE] weathered wood paint, slatted timber, cotton clothing, soft interior dust motes * [COMPOSITION] vertical 9:16 framing, figure in mid-frame, contemplative shadow space filling the upper portion * [STYLE] introspective psychological cinema still, muted domestic palette, fine 35mm grain * [NEGATIVE CONSTRAINTS] no superhero costumes, no glowing white knight armor, no comic book graphics, no text",
    source_anchor: "Banyak orang terjebak menjadi penyelamat (savior complex) karena takut menghadapi kekosongan hidupnya sendiri. Menghormati proses belajar orang lain sering kali berarti tahu kapan harus diam.",
    reflection_target: "Momen ketika menyadari bahwa dorongan untuk menasihati atau mencampuri masalah orang lain sebenarnya didorong oleh keinginan ego untuk merasa penting."
  },
  {
    page_number: 68,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Welas Asih yang Tanpa Panggung",
    subtitle: "Kebaikan yang paling murni selalu lahir dalam keheningan tanpa saksi dan tanpa pamrih.",
    side_a_text: "Kebaikan yang paling menyejukkan hati selalu terjadi tanpa perlu ada kamera yang merekamnya.",
    visual_concept: "Tangan seorang penjual warung membungkuskan nasi lebih banyak ke dalam kertas bungkus untuk seorang pemulung tua tanpa bicara apa-apa.",
    image_prompt: "[SUBJECT] Hands of an Indonesian roadside food vendor adding extra rice to a takeout package * [ORDINARY INDONESIAN ENVIRONMENT] modest warung makan counter during the midday rush * [HUMAN ACTION / EMOTION] vendor quietly adding an extra ladle of warm rice onto brown food wrapping paper with quiet generosity, no words spoken * [ONE MEANINGFUL DETAIL] steam rising from the fresh white rice onto the brown paper packaging, calloused caring hands * [LIGHTING] bright ambient tropical daylight illuminating the food counter and warm metal trays * [MATERIAL / TEXTURE] brown oil-paper wrapping, steaming white rice grains, metal ladle, textured wooden counter * [COMPOSITION] vertical 9:16 close-up framing, hands and meal centered, blurred warung shelves in background above * [STYLE] authentic humanistic street photography, warm natural colors, honest 35mm grain * [NEGATIVE CONSTRAINTS] no glowing halo of generosity, no smartphone cameras recording, no tears of melodrama, no text",
    source_anchor: "Welas asih sejati tidak membutuhkan panggung media sosial atau pengakuan publik. Ia mengalir wajar seperti air yang membasahi tanah kering tanpa pernah meminta upah.",
    reflection_target: "Pengalaman menerima kebaikan tulus dari orang asing yang sama sekali tidak mengharapkan imbalan apa pun dari kita."
  },
  {
    page_number: 69,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Disiplin Hening Tanpa Menawar",
    subtitle: "Menjaga komitmen laku batin di tengah godaan kenyamanan kasur dan kemalasan raga.",
    side_a_text: "Bagaimana mungkin kamu menuntut kedamaian jiwa yang mulia, kalau untuk bangun sebelum fajar saja kamu masih menawar?",
    visual_concept: "Jam weker mekanik tua di samping tempat tidur kayu saat fajar, seseorang bangun seketika dan duduk tegak tanpa ragu-ragu.",
    image_prompt: "[SUBJECT] An Indonesian person sitting up resolutely on the edge of a bed * [ORDINARY INDONESIAN ENVIRONMENT] simple, unadorned village bedroom in the predawn twilight * [HUMAN ACTION / EMOTION] sitting upright with feet planted firmly on the floor, clear eyes, decisive triumph over sluggishness * [ONE MEANINGFUL DETAIL] a vintage round metal twin-bell alarm clock resting on a wooden stool, its hands pointing to early dawn * [LIGHTING] cold, clear blue predawn light washing through the open doorway, sharp contrast * [MATERIAL / TEXTURE] polished metal clock bells, bare wooden stool, cool cement floor, cotton blanket * [COMPOSITION] vertical 9:16 composition, figure grounded at lower-center, tranquil dark room space rising above * [STYLE] stoic documentary realism, cool restrained color grading, fine film grain * [NEGATIVE CONSTRAINTS] no glowing digital snooze buttons, no lazy cartoon clouds, no dramatic flames, no text",
    source_anchor: "Kematangan spiritual membutuhkan wadah disiplin raga. Bila hal-hal kecil seperti waktu tidur dan bangun saja selalu kau kompromikan, fondasi batinmu akan mudah roboh.",
    reflection_target: "Pengalaman menunda-nunda alarm bangun pagi berkali-kali dan merasakan bagaimana hari itu dimulai dengan rasa bersalah dan terburu-buru."
  },
  {
    page_number: 70,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Menanggalkan Amarah Jalanan di Pintu Rumah",
    subtitle: "Kebiasaan sakral membersihkan residu emosi sebelum melangkah masuk menemui keluarga.",
    side_a_text: "Sebelum kamu melangkah melewati pintu rumah, lepaskan sepatu dan tumpukan amarah jalananmu di teras depan.",
    visual_concept: "Sepasang sepatu kerja ditaruh rapi di rak sepatu teras luar, seseorang menghela napas panjang menatap tanaman hias sebelum mengetuk pintu rumah.",
    image_prompt: "[SUBJECT] An Indonesian commuter standing on the front porch of his home after work * [ORDINARY INDONESIAN ENVIRONMENT] modest residential front veranda lined with potted tropical plants at twilight * [HUMAN ACTION / EMOTION] paused on the welcome mat, hands unbuttoning collar, taking one deep restorative breath to wash away road rage * [ONE MEANINGFUL DETAIL] work shoes neatly aligned beside the threshold, a small wooden shoe rack with children's small sandals nearby * [LIGHTING] warm welcoming light glowing from inside the front door frosted glass * [MATERIAL / TEXTURE] textured doormat, worn leather work shoes, green potted aroid leaves, warm painted timber * [COMPOSITION] vertical 9:16 layout, person standing in lower frame, tranquil evening porch and warm doorway above * [STYLE] heartfelt domestic storytelling, warm evening color palette, soft 35mm grain * [NEGATIVE CONSTRAINTS] no black smoke of anger pouring from body, no cartoon stress thunderclouds, no text",
    source_anchor: "Rumah tanggamu adalah kuil kedamaian. Jangan jadikan anak dan pasanganmu sebagai tempat sampah bagi amarah dan kepenatan yang kau pungut dari jalanan.",
    reflection_target: "Pengalaman pulang ke rumah dalam keadaan lelah dan tanpa sengaja melampiaskan kekesalan pekerjaan kepada orang-orang di rumah yang tidak bersalah."
  },
  {
    page_number: 71,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Sujud di Atas Ubin Dingin Jam Tiga Pagi",
    subtitle: "Tempat paling rendah secara fisik yang justru mengangkat derajat ketenangan jiwamu.",
    side_a_text: "Ketika seluruh analisismu buntu tengah malam, ubin kamar yang dingin selalu siap menampung keningmu yang lelah.",
    visual_concept: "Seseorang bersujud hening di atas sajadah tenun bersahaja di sudut kamar rumah limasan kayu saat dini hari yang sunyi.",
    image_prompt: "[SUBJECT] An Indonesian worshipper in prostration (sujud) * [ORDINARY INDONESIAN ENVIRONMENT] quiet corner of an old wooden village room during the dead of night * [HUMAN ACTION / EMOTION] forehead resting gently on a handwoven prayer rug on the floor, total physical surrender and profound inner quiet * [ONE MEANINGFUL DETAIL] the neat folds of a cotton sarong and bare feet touching the smooth cool cement floor * [LIGHTING] very dim ambient moonlight from a high wall vent, soft edge glow defining the worshipper's quiet form * [MATERIAL / TEXTURE] handwoven cotton prayer rug, cool smooth cement, dark textured timber wall * [COMPOSITION] vertical 9:16 frame, prostrate figure anchored low in the frame, vast quiet dark room space rising above * [STYLE] deeply reverent minimalist photography, rich deep charcoal tones, authentic film grain * [NEGATIVE CONSTRAINTS] no glowing light beams from head, no angel figures, no floating mystical calligraphy, no text",
    source_anchor: "Dalam posisi sujud, kepalamu yang selama ini sombong diletakkan sejajar dengan tanah. Di titik terendah itulah egomu luruh dan kejernihan batin kembali menyala.",
    reflection_target: "Momen ketika merasa sangat buntu dan tidak berdaya, lalu bersujud dalam hening dan mendadak merasakan kelegaan yang tak terlukiskan."
  },
  {
    page_number: 72,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Menahan Diri untuk Tidak Menasihati",
    subtitle: "Kebijaksanaan tertinggi yang sering kali berwujud telinga yang mendengar tanpa menghakimi.",
    side_a_text: "Kenapa begitu sulit bagi kita menahan mulut untuk tidak menasihati seseorang yang hanya butuh didengarkan?",
    visual_concept: "Dua sahabat duduk di bangku teras saat gerimis petang, satu orang bercerita dengan mata berkaca-kaca sementara yang lain mendengarkan dengan penuh keheningan.",
    image_prompt: "[SUBJECT] Two Indonesian friends in their 30s seated together on a wooden porch bench * [ORDINARY INDONESIAN ENVIRONMENT] sheltered veranda of a modest village home during gentle evening rain * [HUMAN ACTION / EMOTION] one friend speaking with emotional honesty while the other listens with complete presence, holding back unsolicited advice * [ONE MEANINGFUL DETAIL] two glass cups of warm tea on the bench between them, undisturbed and cooling slowly * [LIGHTING] soft warm porch lantern glow illuminating their faces against the grey rain backdrop * [MATERIAL / TEXTURE] weathered bench wood, glass cups, damp evening air, soft cotton clothes * [COMPOSITION] vertical 9:16 framing, the two figures centered in mid-ground, quiet rain-streaked garden above * [STYLE] empathetic documentary portraiture, natural intimate tones, fine 35mm grain * [NEGATIVE CONSTRAINTS] no floating speech bubbles, no glowing empathy threads, no melodramatic weeping, no text",
    source_anchor: "Sering kali seseorang tidak membutuhkan ceramah atau solusi pintarmu. Mereka hanya membutuhkan ruang aman tempat kerapuhan mereka diterima tanpa dihakimi.",
    reflection_target: "Pengalaman ketika sedang bersedih dan hanya ingin didengarkan, namun lawan bicara justru sibuk menceramahi dan membandingkan dengan masalahnya sendiri."
  },
  {
    page_number: 73,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Kedewasaan Jiwa di Meja Makan Keluarga",
    subtitle: "Membawa seluruh pencarian spiritual kembali ke hangatnya hidangan sederhana di rumah.",
    side_a_text: "Tanda kedewasaan jiwamu bukan kemampuan melihat hal gaib, melainkan kesabaranmu menafkahi keluarga dengan jujur setiap hari.",
    visual_concept: "Seorang ayah meletakkan amplop gaji bersahaja di atas meja makan kayu di samping piring makan malam bersama istri dan anaknya yang tersenyum hangat.",
    image_prompt: "[SUBJECT] An Indonesian family sharing a simple dinner around a wooden table * [ORDINARY INDONESIAN ENVIRONMENT] modest home dining area warmly lit in the evening * [HUMAN ACTION / EMOTION] father passing a plate of food to his child, sharing a warm quiet smile of contentment with his wife * [ONE MEANINGFUL DETAIL] a modest brown paper envelope of hard-earned wages resting unobtrusively on the edge of the table * [LIGHTING] warm yellow overhead dining lamp creating an intimate pool of golden light around the family * [MATERIAL / TEXTURE] well-worn wooden table, simple ceramic bowls, steamed rice, cotton home clothes * [COMPOSITION] vertical 9:16 portrait framing, family gathered in lower half, warm home interior ceiling above * [STYLE] heartwarming domestic realism, rich golden palette, tactile analog 35mm grain * [NEGATIVE CONSTRAINTS] no glowing golden aura of perfection, no stock-photo fake smiles, no wealth boast graphics, no text",
    source_anchor: "Spiritualitas yang tidak mampu membuatmu menjadi pasangan yang lebih sabar dan orang tua yang lebih bertanggung jawab adalah spiritualitas yang mandul.",
    reflection_target: "Pengalaman menyadari bahwa pekerjaan sederhana yang dilakukan dengan jujur demi menafkahi orang tercinta adalah bentuk ibadah tertinggi."
  },
  {
    page_number: 74,
    chapter_code: "BAB 05",
    chapter_name: "Menjadi Manusia Normal & Seni Berserah",
    title: "Aku Telah Pulang ke Rumah Kesadaran",
    subtitle: "Akhir dari seluruh pengembaraan batin: menemukan keagungan semesta di dalam hidup yang biasa.",
    side_a_text: "Setelah mencari ke mana-mana, ternyata yang paling sulit adalah pulang.",
    visual_concept: "Secangkir kopi tubruk hitam yang sudah berkurang setengahnya di atas meja makan kayu keluarga saat senja; di latar belakang yang hangat, pintu kamar terbuka sedikit memperlihatkan anak yang tertidur lelap.",
    image_prompt: "[SUBJECT] A simple glass cup of black tubruk coffee half-drunk on a rustic wooden dining table * [ORDINARY INDONESIAN ENVIRONMENT] quiet evening in an ordinary modest Indonesian home * [HUMAN ACTION / EMOTION] feeling of profound homecoming, stillness, and completion after an immense inner journey * [ONE MEANINGFUL DETAIL] an open doorway in the warm blurred background revealing a small child sleeping peacefully under a thin blanket * [LIGHTING] warm amber lamplight mixing with the deep indigo twilight visible through a small window * [MATERIAL / TEXTURE] dark coffee grounds settled at the bottom of the glass, unvarnished teak table grain, soft cotton bedding * [COMPOSITION] vertical 9:16 layout, coffee cup resting in sharp focus in lower third, peaceful domestic bedroom scene softly blurred above * [STYLE] deeply moving poetic realism, warm nostalgic tones, authentic 35mm film grain * [NEGATIVE CONSTRAINTS] no cosmic galaxies floating in the room, no glowing spiritual figures, no greeting card quotes, no text, no watermark",
    source_anchor: "Seluruh pencarian rahasia langit dan bumi akan membawamu kembali ke titik awal: menghargai secangkir kopi, menyayangi keluargamu, dan menikmati indahnya hidup biasa dengan penuh rasa syukur.",
    reflection_target: "Momen kelegaan luar biasa saat menyadari bahwa seluruh pencarian hidup ini bermuara pada kepulangan: menerima diri apa adanya dan mencintai kehidupan yang bersahaja."
  }
];
