module.exports = [
  {
    page_number: 46,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    subtitle: "Ketika Sains Modern Mulai Mengejar Kebijaksanaan Mistis Nusantara",
    side_a_text: "Kalau seluruh atom di tubuhmu pernah menyatu saat semesta meledak, kenapa malam ini kamu merasa sendirian?",
    visual_concept: "Seorang pria duduk termenung di bangku kayu warkop pinggir jalan Jawa yang remang, uap tipis dari cangkir kopi tubruk di depannya naik perlahan berpilin tenang ke udara malam.",
    image_prompt: "[SUBJECT] A solitary Indonesian man in his early 30s sitting quietly * [ORDINARY INDONESIAN ENVIRONMENT] weathered teak bench at a quiet roadside coffee warung in rural Java at night * [HUMAN ACTION / EMOTION] hands resting beside a hot glass of black coffee, gazing softly into the middle distance in peaceful solitary reflection * [ONE MEANINGFUL DETAIL] fine steam rising straight and undisturbed from the hot black coffee, catching a sliver of warm amber bulb light * [LIGHTING] low-intensity warm incandescent bulb overhead contrasting with the deep indigo night outside * [MATERIAL / TEXTURE] rough aged wood grain, smooth glass, deep shadows, damp night air * [COMPOSITION] vertical 9:16 layout, man and coffee positioned in lower half, dark tranquil negative space rising above * [STYLE] atmospheric Indonesian indie cinema still, analog 35mm film grain, deep charcoal shadows * [NEGATIVE CONSTRAINTS] no glowing cosmic nebulas in coffee, no neon quantum grids, no floating sci-fi equations, no text, no watermark",
    source_anchor: "Fisika kuantum membuktikan bahwa pada tingkat paling mendasar, tidak ada materi yang benar-benar terpisah. Rasa kesepian kita hanyalah ilusi dari keterbatasan panca-indra.",
    reflection_target: "Pengalaman duduk sendirian di warung kopi malam hari dan mendadak merasa asing dari dunia, lalu tersadar bahwa napas dan keberadaan kita sesungguhnya terhubung dengan segala hal."
  },
  {
    page_number: 47,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Kenapa Kita Sering Merasa Sendirian?",
    subtitle: "Ilusi keterpisahan yang diciptakan oleh dinding panca-indra yang sempit.",
    side_a_text: "Pernahkah kamu memikirkan seorang kawan lama, dan beberapa detik kemudian ponselmu berdering menampilkan namanya?",
    visual_concept: "Dua orang duduk di bangku warkop berbeda yang berdekatan saat hujan, saling bertatapan sekilas dengan senyum simpul saat menyadari mereka memesan kopi yang sama.",
    image_prompt: "[SUBJECT] Two ordinary Indonesian strangers sitting at adjacent small wooden tables * [ORDINARY INDONESIAN ENVIRONMENT] cozy traditional coffee stall during a rain shower * [HUMAN ACTION / EMOTION] looking up simultaneously with a quiet smile of unspoken mutual recognition * [ONE MEANINGFUL DETAIL] a shared puddle on the floorboards reflecting the soft golden light from the warung's main hanging lamp * [LIGHTING] warm amber lamplight contrasting with the cool blue rainy twilight outside * [MATERIAL / TEXTURE] wet timber floor, simple glass mugs, weathered raincoats hanging on wall hooks * [COMPOSITION] vertical 9:16 framing, the two tables grounded in mid-lower frame, calm shadowy eaves above * [STYLE] authentic slice-of-life street documentary, naturalistic color palette, fine 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing psychic telepathy rays, no sci-fi floating lines connecting minds, no text",
    source_anchor: "Keterikatan kuantum (quantum entanglement) menjelaskan bagaimana dua partikel yang pernah terhubung akan selalu saling merespons seketika, sejauh apa pun jaraknya.",
    reflection_target: "Pengalaman mengalami firasat atau kebetulan batin yang terlalu pas dan presisi untuk disebut sekadar peristiwa acak."
  },
  {
    page_number: 48,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Dua Partikel yang Tak Pernah Berpisah",
    subtitle: "Keterikatan kuantum di dalam ikatan batin antarmanusia.",
    side_a_text: "Dua cangkir kopi yang dipesan di meja berbeda, tapi diseduh dari air mendidih yang sama.",
    visual_concept: "Dua cangkir teh poci tanah liat diletakkan di atas baki kayu di dapur warkop, uap hangat keduanya menyatu di udara sebelum disajikan ke meja tamu.",
    image_prompt: "[SUBJECT] Two traditional unglazed terracotta tea cups (cangkir poci) on a weathered wooden tray * [ORDINARY INDONESIAN ENVIRONMENT] kitchen counter of a traditional Javanese tea house (angkringan) * [HUMAN ACTION / EMOTION] an elderly server's hands setting down the tray with gentle, unhurried care * [ONE MEANINGFUL DETAIL] the gentle wisps of steam from both cups naturally mingling into a single soft swirl in the air * [LIGHTING] soft morning window light highlighting the earthen clay texture and steam * [MATERIAL / TEXTURE] rough reddish clay, worn teak wood, warm rising steam, natural linen cloth * [COMPOSITION] vertical 9:16 layout, tea tray centered in lower third, quiet shadowy kitchen backdrop filling upper space * [STYLE] contemplative still-life editorial, organic earth tones, tactile film grain * [NEGATIVE CONSTRAINTS] no glowing particle physics diagrams, no laser entanglement threads, no CGI atoms, no text",
    source_anchor: "Dua entitas yang pernah berbagi medan energi yang sama akan selalu mempertahankan resonansi batin, persis seperti dua partikel kuantum yang tak pernah benar-benar terpisah.",
    reflection_target: "Pengalaman merasakan hubungan batin yang kuat dengan orang tua, pasangan, atau sahabat meskipun sedang terpisah jarak ribuan kilometer."
  },
  {
    page_number: 49,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Darahmu Mengalir dari Tungku Bintang Purba",
    subtitle: "Unsur kimia di dalam sel ragamu adalah debu kosmis yang telah mengembara miliaran tahun.",
    side_a_text: "Besi di dalam sel darah merahmu ditempa di jantung bintang yang meledak miliaran tahun lalu.",
    visual_concept: "Seorang petani tua duduk di pematang sawah memegang segumpal tanah subur di telapak tangannya, menatap butiran tanah yang berkilau lembut diterpa sinar fajar.",
    image_prompt: "[SUBJECT] Weathered hands of an Indonesian farmer holding a clump of dark moist soil * [ORDINARY INDONESIAN ENVIRONMENT] edge of a terraced rice field at sunrise * [HUMAN ACTION / EMOTION] gently crumbling the fertile earth between thumb and fingers with profound instinctive gratitude * [ONE MEANINGFUL DETAIL] tiny mineral specks in the black volcanic soil catching the low golden rays of the morning sun * [LIGHTING] dramatic low-angle morning sunlight highlighting hand textures and crumbly soil * [MATERIAL / TEXTURE] dark rich volcanic loam, weathered calloused skin, glistening dew droplets * [COMPOSITION] vertical 9:16 close-up framing, hands and soil in lower half, soft misty green field receding into upper frame * [STYLE] poetic agricultural documentary, warm organic colors, rich 35mm grain * [NEGATIVE CONSTRAINTS] no galaxy superimposed on hands, no glowing space dust effects, no sci-fi planetary explosion overlays, no text",
    source_anchor: "Setiap atom besi yang mengikat oksigen dalam darahmu berasal dari fusi nuklir di inti bintang purba. Secara harfiah dan biologis, ragamu adalah materi semesta yang sedang sadar.",
    reflection_target: "Momen ketika menyadari betapa kerdil namun agungnya eksistensi diri kita sebagai bagian tak terpisahkan dari sejarah semesta."
  },
  {
    page_number: 50,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Waktu Sebenarnya Cuma Kesepakatan Sosial",
    subtitle: "Mengapa satu jam di ruang tunggu terasa selamanya, sementara satu malam bersama kekasih berlalu sekejap.",
    side_a_text: "Jarum jam di dindingmu berputar kencang, tapi kenapa luka sepuluh tahun lalu masih berdenyut segar?",
    visual_concept: "Sebuah jam dinding bandul kayu tua di dinding rumah joglo desa, seorang kakek duduk tenang di bawahnya tanpa pernah melirik ke arah jarum jam.",
    image_prompt: "[SUBJECT] An elderly Indonesian grandfather sitting peacefully in a rattan armchair * [ORDINARY INDONESIAN ENVIRONMENT] quiet main living room of an old wooden Javanese house * [HUMAN ACTION / EMOTION] hands resting on chair arms, gaze settled on the open doorway, completely detached from the passage of clock time * [ONE MEANINGFUL DETAIL] a vintage wooden mechanical wall pendulum clock hanging high on the lime-washed wall behind him, ticking steadily * [LIGHTING] afternoon golden light spilling through the doorway, casting soft elongated shadows across the floor * [MATERIAL / TEXTURE] woven rattan, aged teak wall clock, chalky lime plaster wall, soft cotton sarong * [COMPOSITION] vertical 9:16 layout, grandfather seated in lower-middle frame, clock positioned higher up, quiet vertical harmony * [STYLE] timeless domestic portraiture, warm nostalgic palette, authentic film grain * [NEGATIVE CONSTRAINTS] no melting Dali clocks, no glowing time-travel vortex, no digital countdown numbers, no text",
    source_anchor: "Waktu bukanlah garis lurus objektif, melainkan persepsi subjektif kesadaran. Luka batin masa lalu terasa baru kemarin karena pikiran bawah sadar tidak mengenal konsep jam.",
    reflection_target: "Pengalaman menyadari bagaimana kenangan emosional masa kecil atau masa remaja bisa terasa begitu dekat seolah baru terjadi kemarin sore."
  },
  {
    page_number: 51,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Ketika Akibat Mendahului Sebab",
    subtitle: "Retrokausalitas dan keyakinan hati yang menarik peristiwa masa depan ke masa kini.",
    side_a_text: "Rasa cukup yang kau rasakan di dada pagi ini sudah memanggil rezeki yang bahkan belum berangkat dari asalnya.",
    visual_concept: "Sepiring nasi hangat dengan tempe goreng bersahaja di atas meja kayu dapur pawon, seseorang menyatukan kedua tangan sejenak dalam rasa syukur yang utuh sebelum makan.",
    image_prompt: "[SUBJECT] A simple Indonesian family meal setting on an unpainted wooden table * [ORDINARY INDONESIAN ENVIRONMENT] humble kitchen with woven bamboo walls in morning light * [HUMAN ACTION / EMOTION] a person pausing with hands resting beside the plate, head bowed in brief, quiet, sincere gratitude * [ONE MEANINGFUL DETAIL] steam gently drifting off a portion of freshly steamed white rice and crispy fried tempeh on a vintage enamel plate * [LIGHTING] soft morning daylight entering from a small window, warming the steam and wood * [MATERIAL / TEXTURE] chipped floral enamel plate, fresh banana leaf liner, rough teak table, honest food textures * [COMPOSITION] vertical 9:16 frame, the plate and hands grounded in lower half, warm shadowy kitchen rafters above * [STYLE] warm cultural realism, rich textural authenticity, 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing golden aura over food, no money raining down, no fantasy blessing beams, no text",
    source_anchor: "Dalam mekanika kuantum, keadaan pengamat di masa kini dapat mempengaruhi probabilitas peristiwa. Ketika rasa cukup dan syukur telah hadir lebih dulu, kenyataan fisik akan mengikuti.",
    reflection_target: "Momen ketika merasa begitu tenang dan tidak khawatir tentang masa depan, dan mendadak jalan keluar dari masalah datang secara tak terduga."
  },
  {
    page_number: 52,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Realitas Tergantung ke Mana Matamu Menatap",
    subtitle: "Observer effect: bagaimana kehadiran tatapanmu mengubah gelombang kemungkinan menjadi materi padat.",
    side_a_text: "Dunia di depanmu berubah wujud tergantung prasangka apa yang kau bawa di kedua matamu.",
    visual_concept: "Seseorang berdiri di puncak bukit desa menatap kabut fajar yang perlahan tersibak memperlihatkan atap-atap rumah dan pepohonan hijau di bawahnya.",
    image_prompt: "[SUBJECT] An Indonesian person seen from behind standing on a grassy hillside * [ORDINARY INDONESIAN ENVIRONMENT] hill overlooking a village valley in rural Java at dawn * [HUMAN ACTION / EMOTION] standing motionless, watching the dense morning fog gradually part to reveal the valley below * [ONE MEANINGFUL DETAIL] a clear break in the morning fog directly along the line of sight, revealing green village rooftops * [LIGHTING] pale pearl-grey dawn light slowly warming with golden morning rays * [MATERIAL / TEXTURE] damp morning grass, cool mountain mist, coarse jacket fabric, distant clay roof tiles * [COMPOSITION] vertical 9:16 composition, watcher standing in lower third, vast misty landscape and sky filling upper frame * [STYLE] contemplative landscape photography, gentle color transitions, organic film grain * [NEGATIVE CONSTRAINTS] no glowing laser eyes, no digital heads-up display, no quantum particle grids floating, no text",
    source_anchor: "Eksperimen celah ganda membuktikan partikel bertindak sebagai gelombang probabilitas sampai seorang pengamat mengamatinya. Cara pandangmu secara harfiah meruntuhkan kemungkinan menjadi kenyataan hidup.",
    reflection_target: "Pengalaman menyadari bahwa saat kita mencurigai seseorang, setiap tindakannya akan terlihat mencurigakan; namun saat kita memandang dengan kasih, segalanya terasa berbeda."
  },
  {
    page_number: 53,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Meleburnya Sekat Antara Dirimu dan Sang Maha Ada",
    subtitle: "Bukan menyatukan dua zat yang berbeda, melainkan menyadari bahwa sekat itu sejak awal tak pernah ada.",
    side_a_text: "Tetesan air wudu yang luruh ke permukaan sungai fajar menyatu kembali tanpa menyisakan bekas sekat.",
    visual_concept: "Tangan seseorang mencelup ke dalam aliran sungai jernih di pedesaan saat subuh, air mengalir tenang di sela jemari tanpa perlawanan.",
    image_prompt: "[SUBJECT] A hand of an Indonesian worshipper or villager submerged in clean river water * [ORDINARY INDONESIAN ENVIRONMENT] quiet shallow riverbank in rural Java at dawn * [HUMAN ACTION / EMOTION] hand resting gently in the clear current, fingers slightly parted, allowing the cold river water to flow freely over the skin * [ONE MEANINGFUL DETAIL] small natural ripples diverging around the wrist and re-merging seamlessly downstream * [LIGHTING] soft cool blue dawn light reflecting off the moving water surface * [MATERIAL / TEXTURE] smooth river stones under clear water, cool skin, rippling liquid surface * [COMPOSITION] vertical 9:16 top-down angle, hand and stream centered in lower frame, reflective dark water surface expanding upwards * [STYLE] serene tactile nature photography, clean organic color grade, 35mm grain * [NEGATIVE CONSTRAINTS] no glowing holy halos, no divine faces in the water, no glowing runes, no text",
    source_anchor: "Konsep manunggal dalam mistisisme Jawa sering disalahpahami sebagai penyatuan fisik. Padahal ia adalah kesadaran bahwa sekat antara hamba dan Sang Khalik hanyalah kabut tebal ego.",
    reflection_target: "Pengalaman merasakan kedamaian mutlak saat menyerahkan seluruh kehendak pribadi dan membiarkan hidup berjalan sesuai kehendak-Nya."
  },
  {
    page_number: 54,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Perjalanan Jiwa Menuju Manusia Utuh",
    subtitle: "Tanda kedewasaan batin bukanlah kemampuan melihat gaib, melainkan welas asih pada sesama.",
    side_a_text: "Ketinggian ilmu seseorang tidak diukur dari hafalan rumusnya, melainkan kehangatan senyumnya saat menyapa penjual tempe.",
    visual_concept: "Seseorang yang pulang dari surau desa pagi hari berhenti di jalan kampung, menyapa seorang nenek penjual sayur keliling dengan senyum tulus dan membungkukkan badan.",
    image_prompt: "[SUBJECT] An Indonesian man in clean simple sarong and shirt interacting with an elderly vegetable vendor * [ORDINARY INDONESIAN ENVIRONMENT] quiet village lane in Java lined with banana plants at morning * [HUMAN ACTION / EMOTION] bowing slightly in genuine Javanese courtesy (andhap asor), exchanging a warm, sincere smile with the vendor * [ONE MEANINGFUL DETAIL] the vendor's traditional woven bamboo basket (tenggok) filled with fresh green vegetables and banana-leaf-wrapped tempeh * [LIGHTING] warm morning sunlight filtering through coconut trees, dappled cheerful light on the path * [MATERIAL / TEXTURE] worn asphalt path, woven bamboo, fresh leafy greens, cotton clothing * [COMPOSITION] vertical 9:16 framing, human interaction in lower-mid frame, peaceful village road receding into morning light above * [STYLE] heartfelt documentary portraiture, warm saturated earthy colors, authentic film grain * [NEGATIVE CONSTRAINTS] no glowing aura of saintliness, no floating hearts, no religious iconography, no text",
    source_anchor: "Puncak pemahaman atas keterhubungan semesta selalu berbuah welas asih. Bila ilmumu makin tinggi tapi kamu makin sinis dan meremehkan orang awam, berarti kamu baru menumpuk sampah konsep.",
    reflection_target: "Pengalaman bertemu orang yang sangat berilmu atau spiritual namun kepribadiannya begitu bersahaja, hangat, dan tidak merasa lebih tinggi dari siapa pun."
  },
  {
    page_number: 55,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Sebelas Tembang Siklus Perjalanan Jiwa",
    subtitle: "Peta macapat Jawa yang memetakan evolusi kesadaran dari kandungan hingga kembali ke keabadian.",
    side_a_text: "Di balik kelir wayang, kelahiran dan kepulangan hanyalah dua adegan berbeda dari satu lakon yang sama.",
    visual_concept: "Sebuah wayang kulit purwa tersandar di batang pisang (gedebog) di pendopo kosong saat pertunjukan telah usai, lampu blencong temaram padam perlahan.",
    image_prompt: "[SUBJECT] A solitary leather wayang puppet standing planted in a banana trunk base (gedebog) * [ORDINARY INDONESIAN ENVIRONMENT] empty open pendopo pavilion after a midnight performance * [HUMAN ACTION / EMOTION] no humans present; feeling of deep stillness and the solemn conclusion of life's grand theater * [ONE MEANINGFUL DETAIL] the fine hand-carved perforations of the leather puppet casting subtle shadows on the worn wooden floor * [LIGHTING] faint dying embers of a traditional hanging brass oil lamp, mixed with cool blue midnight ambient light * [MATERIAL / TEXTURE] carved water buffalo leather, natural fiber banana stem, aged teak floorboards * [COMPOSITION] vertical 9:16 layout, puppet resting in lower-center, vast quiet dark pendopo space rising above * [STYLE] poetic cultural fine art photography, high tonal depth, rich analog 35mm grain * [NEGATIVE CONSTRAINTS] no glowing souls rising into sky, no reincarnation spiral graphics, no cartoon fantasy spirits, no text",
    source_anchor: "Sebelas tembang macapat (mulai dari Maskumambang hingga Megatruh dan Pucung) adalah algoritma spiritual leluhur yang menggambarkan siklus perjalanan jiwa melintasi ruang dan waktu.",
    reflection_target: "Pengalaman merenungi perjalanan hidup sendiri dari masa kanak-kanak hingga saat ini, dan merasakan adanya alur besar yang membimbing di balik semua peristiwa."
  },
  {
    page_number: 56,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Menikmati Secangkir Kopi Tanpa Menjajah Masa Depan",
    subtitle: "Seni berada di sini dan saat ini tanpa ditarik oleh kecemasan hari esok.",
    side_a_text: "Menyesap secangkir kopi hangat tanpa buru-buru memikirkan pekerjaan yang menunggumu sejam lagi.",
    visual_concept: "Seseorang duduk sendirian di teras warung kopi sederhana, kedua tangan memegang cangkir hangat, mata terpejam sesaat menikmati aroma kopi tanpa membuka ponsel.",
    image_prompt: "[SUBJECT] An Indonesian person sitting quietly on a wooden stool outside a rustic village coffee stall * [ORDINARY INDONESIAN ENVIRONMENT] open wooden porch overlooking a tranquil garden in the late afternoon * [HUMAN ACTION / EMOTION] holding a small steaming ceramic cup to chest level, eyes softly closed, completely immersed in the simple sensory present moment * [ONE MEANINGFUL DETAIL] a smartphone left tucked inside a jacket pocket, completely out of sight and mind * [LIGHTING] gentle amber afternoon golden hour light illuminating the steam and warm facial expression * [MATERIAL / TEXTURE] rough wood grain of the bench, warm glazed ceramic, soft cotton shirt, cool afternoon air * [COMPOSITION] vertical 9:16 portrait framing, person centered in lower two-thirds, tranquil foliage and sky above * [STYLE] mindful lifestyle photography, warm naturalistic palette, soft filmic grain * [NEGATIVE CONSTRAINTS] no floating clock icons, no future stress thought bubbles, no coffee brand logos, no text",
    source_anchor: "Pikiran selalu ingin lari ke masa lalu yang sudah mati atau masa depan yang belum lahir. Hadir utuh di satu tegukan kopi hari ini adalah cara paling sederhana meruntuhkan ilusi waktu.",
    reflection_target: "Pengalaman betapa sulitnya menikmati momen makan atau minum santai karena kepala kita terus sibuk memikirkan daftar tugas dan masalah yang belum terjadi."
  },
  {
    page_number: 57,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Bisikan Halus di Dasar Hati Tanpa Pamrih",
    subtitle: "Ketika tindakan kebaikan dilakukan murni tanpa mengharapkan validasi atau tepuk tangan.",
    side_a_text: "Kebaikan paling murni yang pernah kau lakukan adalah saat tangan kirimu tak sempat menghitung jasa tangan kananmu.",
    visual_concept: "Tangan seseorang meletakkan bungkusan makanan bersahaja di atas beranda bambu rumah tetangga lansia saat fajar membiru secara diam-diam.",
    image_prompt: "[SUBJECT] Close-up of a hand quietly placing a wrapped food parcel * [ORDINARY INDONESIAN ENVIRONMENT] wooden veranda of a humble village house in rural Java during early dawn * [HUMAN ACTION / EMOTION] setting down a traditional banana-leaf-wrapped parcel with gentle, silent care and immediately withdrawing * [ONE MEANINGFUL DETAIL] the banana leaf package tied with natural bamboo string, resting securely on the clean wooden porch * [LIGHTING] cool deep dawn twilight, quiet soft illumination without direct sun * [MATERIAL / TEXTURE] fresh green banana leaf, split bamboo string, weathered grey wood porch * [COMPOSITION] vertical 9:16 frame, parcel and hand in lower third, quiet village dawn background stretching above * [STYLE] humble observational documentary, quiet emotional resonance, 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing halo of charity, no golden angel wings, no dramatic spotlight, no text",
    source_anchor: "Resonansi medan karma yang paling bersih tercipta dari kebaikan anonim yang dilakukan tanpa pamrih pembuktian diri. Di titik itu, egomu lebur ke dalam welas asih semesta.",
    reflection_target: "Pengalaman menolong seseorang secara diam-diam tanpa ada yang tahu, dan merasakan kebahagiaan batin yang jauh lebih dalam dibanding dipuji orang banyak."
  },
  {
    page_number: 58,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Dunia Luar Cuma Layar Bioskop Pikiranmu",
    subtitle: "Berhenti bertengkar dengan bayangan di layar; tengoklah proyektor di belakang kepalamu.",
    side_a_text: "Bayangan siluetmu di layar putih bioskop bukanlah dirimu; kamu adalah proyektor cahaya yang menyalakannya.",
    visual_concept: "Seorang penonton berdiri sendirian di aula bioskop tua atau pendopo kelir layar putih, memandangi bayangan siluet tubuhnya sendiri yang terproyeksi di hadapannya.",
    image_prompt: "[SUBJECT] Silhouette of an Indonesian person standing before a large projection screen * [ORDINARY INDONESIAN ENVIRONMENT] vintage theater hall or open-air shadow play space * [HUMAN ACTION / EMOTION] standing completely still, looking at their own sharp dark shadow cast onto the wide neutral screen * [ONE MEANINGFUL DETAIL] a clean beam of white projector light cutting through the dusty room air overhead, illuminating floating dust motes * [LIGHTING] single powerful projector beam from behind casting high-contrast shadow against bright cloth * [MATERIAL / TEXTURE] white stretched cotton screen, wooden floor, dust particles in beam of light * [COMPOSITION] vertical 9:16 composition, figure anchored at bottom-center, towering white screen and light cone filling upper frame * [STYLE] artistic psychological photography, strong monochrome contrast with warm amber undertones, 35mm grain * [NEGATIVE CONSTRAINTS] no movie graphics on screen, no glowing holographic illusions, no sci-fi lasers, no text",
    source_anchor: "Seluruh peristiwa hidup yang kamu alami di luar hanyalah proyeksi dari keyakinan batinmu. Mengubah nasib dengan menyerang dunia luar sama konyolnya dengan memukul layar bioskop agar jalan cerita film berubah.",
    reflection_target: "Pengalaman menyadari bahwa kemarahan kita pada orang lain sering kali merupakan pantulan dari ketidakpuasan kita terhadap diri sendiri."
  },
  {
    page_number: 59,
    chapter_code: "BAB 04",
    chapter_name: "Fisika Kuantum, Relativitas & Keterhubungan Semesta",
    title: "Menatap Seluruh Semesta di Dalam Cangkir Kopi",
    subtitle: "Semua jalinan kuantum berpulang pada keheningan: suwung kang isi, isi kang suwung.",
    side_a_text: "Seluruh kerumitan rumus semesta pada akhirnya luruh kembali ke dalam ketenangan secangkir kopi di mejamu.",
    visual_concept: "Permukaan mangkuk kopi tanah liat hitam legam tanpa riak di atas meja kayu pedesaan saat malam hening, memantulkan sepotong langit malam dan sehelai daun bambu di atasnya.",
    image_prompt: "[SUBJECT] An unglazed traditional clay cup filled with still black coffee * [ORDINARY INDONESIAN ENVIRONMENT] rustic outdoor wooden table in a rural Javanese garden at night * [HUMAN ACTION / EMOTION] solitary contemplation; feeling of profound homecoming to simplicity after exploring cosmic mysteries * [ONE MEANINGFUL DETAIL] the pitch-black mirror surface of the coffee reflecting faint starlight and a dark bamboo leaf silhouette * [LIGHTING] deep indigo nocturnal atmosphere with soft ambient starlight and faint distant porch glow * [MATERIAL / TEXTURE] rough porous terracotta cup, perfectly still liquid mirror, weathered table grain * [COMPOSITION] vertical 9:16 layout, cup resting firmly on table in lower third, deep tranquil night sky rising above * [STYLE] serene minimalist photography, velvety deep blacks, tactile 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing cosmic galaxies inside coffee, no fantasy energy spirals, no sci-fi portals, no text, no watermark",
    source_anchor: "Suwung bukanlah kehampaan mati, melainkan samudra hening tempat seluruh kemungkinan semesta tercipta dan berpulang. Di dalam keheningan itulah rumah sejatimu.",
    reflection_target: "Momen ketika setelah memikirkan banyak hal rumit tentang hidup dan semesta, kita akhirnya merasa cukup hanya dengan duduk tenang menikmati secangkir kopi."
  }
];
