module.exports = [
  {
    page_number: 1,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Anatomi Tubuh Energi & Memori Karma",
    subtitle: "Ketika Raga Mengingat Apa yang Dilupakan Pikiran",
    side_a_text: "Pernahkah tubuhmu mengingat sesuatu yang kepalamu sendiri sudah menyerah mengingatnya?",
    visual_concept: "Seseorang duduk diam di balai kayu tua saat dini hari, menatap kedua telapak tangannya sendiri yang terbuka di atas lutut dalam keheningan yang intim.",
    image_prompt: "[SUBJECT] A contemplative Indonesian man in his late 20s wearing a simple faded dark linen shirt * [ORDINARY INDONESIAN ENVIRONMENT] interior of an old weathered Javanese joglo house at dawn * [HUMAN ACTION / EMOTION] sitting quietly on a wooden bench, gazing down at his own open hands resting on his knees with quiet introspection * [ONE MEANINGFUL DETAIL] faint morning dust motes catching a single narrow shaft of grey dawn light from a wooden wall slat * [LIGHTING] soft directional morning daylight mixed with deep charcoal ambient shadows * [MATERIAL / TEXTURE] rough aged teak grain, worn terracotta floor, coarse cotton fabric * [COMPOSITION] vertical 9:16 portrait composition, subject positioned in lower half, generous quiet negative space in upper third * [STYLE] restrained cinematic analog 35mm film still, muted earthy palette, authentic film grain * [NEGATIVE CONSTRAINTS] no glowing aura, no fantasy chakras, no floating energy rings, no CGI illustration, no digital sharpness, no text, no watermark",
    source_anchor: "Tubuh ini bukan sekadar tumpukan daging dan tulang. Ia adalah kuil hidup yang menyimpan seluruh rekaman perjalanan sukmamu, jauh sebelum pikiranmu sempat merumuskannya.",
    reflection_target: "Pengalaman ketika reaksi fisik atau getaran di tubuh mendahului logika berpikir saat menghadapi momen penting."
  },
  {
    page_number: 2,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Ketika Tubuhmu Tahu Duluan",
    subtitle: "Ragamu sudah membaca ruang jauh sebelum kepalamu sempat bertanya.",
    side_a_text: "Kenapa tubuhmu kadang mengenali tempat yang seumur hidup belum pernah kau datangi?",
    visual_concept: "Seseorang berhenti melangkah di mulut gang sempit berbatu basah seusai gerimis petang di Jogja, menatap kelokan jalan dengan kebingungan akrab.",
    image_prompt: "[SUBJECT] A solitary young Indonesian man seen from behind and side, wearing an ordinary canvas jacket * [ORDINARY INDONESIAN ENVIRONMENT] entrance of a narrow residential alleyway in Yogyakarta after evening rain * [HUMAN ACTION / EMOTION] pausing mid-stride, turning slightly toward an unlit corner with a sense of sudden quiet familiarity * [ONE MEANINGFUL DETAIL] wet asphalt and damp stone pavement reflecting a single warm tungsten streetlamp hanging from an old wooden post * [LIGHTING] dusk twilight falling, warm golden sodium glow contrasting cool blue ambient wetness * [MATERIAL / TEXTURE] damp brickwork, mossy plaster walls, reflective puddles, tactile 35mm grain * [COMPOSITION] vertical 9:16 editorial framing, figure occupying mid-ground, spacious clean negative space overhead * [STYLE] intimate realism, documentary film aesthetic, muted terracotta and charcoal tones * [NEGATIVE CONSTRAINTS] no ghosts, no supernatural apparitions, no glowing lines, no fantasy elements, no text, no typography",
    source_anchor: "Sudut gang tua yang seumur hidup belum pernah kamu lewati... Begitu kakimu menginjak tanah di situ, mendadak dadamu berdesir hebat: 'Lho, aku pernah di sini.'",
    reflection_target: "Pengalaman mengalami deja vu fisik yang begitu nyata hingga membuat bulu kuduk merinding di tempat asing."
  },
  {
    page_number: 3,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Mengetuk Meja Kayu & Medan Magnet Dada",
    subtitle: "Rasa itu bukan hantu; ia gelombang elektromagnetik yang nyata.",
    side_a_text: "Dadamu berdesir bukan karena kabel di otakmu konslet, melainkan karena ragamu sedang membaca frekuensi.",
    visual_concept: "Ujung jemari tangan seorang pria mengetuk permukaan meja kayu jati tua di warung kopi remang, secangkir kopi tubruk hitam mengepul di sampingnya.",
    image_prompt: "[SUBJECT] Close-up of a weathered Indonesian man's hand resting on a rustic wooden table * [ORDINARY INDONESIAN ENVIRONMENT] dimly lit traditional Javanese roadside warung at night * [HUMAN ACTION / EMOTION] fingers lightly tapping the grooved wood surface in quiet contemplation * [ONE MEANINGFUL DETAIL] steam rising straight and undisturbed from a small glass cup of black tubruk coffee beside the hand * [LIGHTING] warm amber practical light from a low-hanging incandescent bulb casting long soft shadows * [MATERIAL / TEXTURE] deeply textured aged teak grain with varnish cracks, warm ceramic, damp dark background * [COMPOSITION] vertical 9:16 framing, hand and coffee cup grounded in lower third, calm empty dark negative space above * [STYLE] tactile cinematic photography, deep shadows, rich charcoal and sepia tones, 35mm film texture * [NEGATIVE CONSTRAINTS] no sci-fi magnetic rings, no glowing neon fields, no computer graphics, no text, no watermark",
    source_anchor: "Begitu ujung jarimu mengetuk meja kayu di depanmu, ada getaran mikro yang merambat... Jantungmu itu pusat pembangkit elektromagnetik terbesar di tubuhmu.",
    reflection_target: "Momen ketika duduk sendirian di warung kopi dan tiba-tiba menyadari denyut kehadiran diri serta benda-benda di sekitar tanpa memikirkan apa-apa."
  },
  {
    page_number: 4,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Medan Torus & Donat Gaib di Dadamu",
    subtitle: "Dadamu memancarkan pusaran rasa yang menembus dinding dan pakaian.",
    side_a_text: "Bahkan sebelum mulutmu sempat menyapa, orang lain sudah tahu apakah hatimu sedang hangat atau dingin.",
    visual_concept: "Dua orang duduk berhadapan di bangku panjang warung makan bambu bersahaja tanpa bicara, dihubungkan oleh keheningan yang saling memahami.",
    image_prompt: "[SUBJECT] Two Indonesian men in everyday casual clothing seated across from each other * [ORDINARY INDONESIAN ENVIRONMENT] open-air modest wooden village warung late in the afternoon * [HUMAN ACTION / EMOTION] sitting in quiet comfortable silence without looking at phones, shared presence without spoken words * [ONE MEANINGFUL DETAIL] two simple enamel tin mugs on the table, their subtle warm steam drifting toward each other before dissipating * [LIGHTING] low-angled golden late afternoon sun filtering through slatted bamboo bamboo blinds * [MATERIAL / TEXTURE] split bamboo walls, worn wooden bench, oxidized tin enamelware, dusty air motes * [COMPOSITION] vertical 9:16 layout, figures in lower half, broad calm background with quiet negative space * [STYLE] naturalistic Indonesian slice-of-life cinema, muted earth colors, analog film grain * [NEGATIVE CONSTRAINTS] no glowing torus graphics, no donut-shaped energy fields, no fantasy overlays, no digital art slop, no text",
    source_anchor: "Medan torus ini bentuknya mirip kue donat atau buah apel... Gelombang rasa di dadamu itu memancar keluar menembus kain bajumu, menembus dinding.",
    reflection_target: "Pengalaman merasakan suasana hati seseorang yang mendadak terasa begitu jelas saat melangkah masuk ke ruangan yang sama."
  },
  {
    page_number: 5,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Kotak Hitam di Pangkal Tulang Ekor",
    subtitle: "Tempat tersimpannya catatan perjalanan yang tak pernah kau tulis.",
    side_a_text: "Pernah kepikiran, kenapa bagian tubuh yang hampir tak pernah kau ingat justru dibicarakan sebagai awal segala sesuatu?",
    visual_concept: "Seseorang duduk bertumpu lelah di undakan batu kali berlumut belakang rumah seusai kerja keras, menatap tanah basah dalam kepasrahan fisik.",
    image_prompt: "[SUBJECT] A tired Indonesian laborer or craftsman in simple dark cotton pants and worn shirt * [ORDINARY INDONESIAN ENVIRONMENT] backyard stone steps of a modest rural house surrounded by wet earth * [HUMAN ACTION / EMOTION] sitting rested heavily on the bottom step, spine naturally curved, resting forearms on knees, gazing quietly at the damp ground * [ONE MEANINGFUL DETAIL] his lower spine and tailbone solidly anchored against the cool weathered river stone, embodying deep somatic grounding * [LIGHTING] overcast daylight after light rain, soft diffused cool shadows * [MATERIAL / TEXTURE] rough river rock, green moss, damp black soil, faded worn fabric * [COMPOSITION] vertical 9:16 composition, subject centered in lower portion, quiet grey negative space in upper frame * [STYLE] gritty honest documentary photography, rich film grain, muted charcoal and slate tones * [NEGATIVE CONSTRAINTS] no glowing coccyx, no red root chakra fire, no mystical symbols, no skeleton xray, no text",
    source_anchor: "Para tetua Jawa dan tradisi kuno menyebut di area tulang ekor inilah tersimpan kundalini atau bibit rekaman karma... seperti kotak hitam pesawat.",
    reflection_target: "Pengalaman ketika tubuh menyimpan rasa lelah dan beban emosi di punggung bawah, sementara pikiran sadar berusaha mengabaikannya."
  },
  {
    page_number: 6,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Karma Bukan Hukuman tapi Resonansi",
    subtitle: "Semesta tidak mendendam; ia hanya memantulkan frekuensi batinmu.",
    side_a_text: "Kalau semesta bukan hakim, lalu kenapa hal yang sama terasa terus kembali kepadamu?",
    visual_concept: "Seorang pria mencuci muka di wastafel warung malam, menatap air yang berputar ke lubang pembuangan sementara matanya di cermin tampak lelah melihat pola hidup yang itu-itu saja.",
    image_prompt: "[SUBJECT] An Indonesian man in his early 30s wiping water from his face * [ORDINARY INDONESIAN ENVIRONMENT] modest outdoor washbasin behind a roadside eatery at night * [HUMAN ACTION / EMOTION] pausing with wet hands on the basin rim, looking at the draining water with a quiet, tired realization * [ONE MEANINGFUL DETAIL] water swirling steadily down the small metal drain, forming a clear natural vortex * [LIGHTING] solitary warm bulb overhead reflecting off the damp cracked mirror and wet ceramic * [MATERIAL / TEXTURE] water droplets on skin, stained concrete sink, tarnished brass faucet * [COMPOSITION] vertical 9:16 composition, figure in middle, dark calm space framing the top * [STYLE] moody cinematic realism, 35mm film grain, deep shadows, charcoal and muted amber * [NEGATIVE CONSTRAINTS] no demonic karmic wheels, no fiery scales of justice, no mystical entities, no text, no typography",
    source_anchor: "Karma itu bukan algojo bertongkat yang siap memukul kepalamu saat kamu berbuat salah. Karma adalah hukum resonansi alami, semacam gema di dinding tebing.",
    reflection_target: "Pengalaman berulang kali mendapati masalah hidup yang polanya mirip meski berganti lingkungan dan teman, lalu bertanya apakah pemicunya ada di respons diri sendiri."
  },
  {
    page_number: 7,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Cairan Otak, Ritme Hening & Jalur Tulang Belakang",
    subtitle: "Jalur air murni yang membasahi akar saraf setiap kali nafasmu melambat.",
    side_a_text: "Pernah memperhatikan betapa cepat pikiran berubah ketika tubuh akhirnya benar-benar diam?",
    visual_concept: "Seseorang duduk bersandar pada dinding plester kapur dingin di dalam kamar rumah limasan saat larut malam, segelas air putih tenang tanpa riak di lantai semen sampingnya.",
    image_prompt: "[SUBJECT] A solitary Indonesian person sitting quietly on the floor with back against a wall * [ORDINARY INDONESIAN ENVIRONMENT] quiet corner of an old village house at night * [HUMAN ACTION / EMOTION] sitting upright yet relaxed, head slightly tilted, eyes softly closed in deep unhurried stillness * [ONE MEANINGFUL DETAIL] a clear glass tumbler of water placed on the smooth cool cement floor beside them, perfectly still without a single ripple * [LIGHTING] dim soft moonlight entering through high ventilation wooden slats * [MATERIAL / TEXTURE] whitewashed lime plaster wall, cool grey cement floor, clear water glass * [COMPOSITION] vertical 9:16 frame, quiet vertical posture echoing the straight wall line, ample breathing space above * [STYLE] contemplative minimalist photography, muted monochrome palette with warm undertones, fine grain * [NEGATIVE CONSTRAINTS] no glowing spinal cords, no fiber optic cables in spine, no x-ray visuals, no alien lights, no text",
    source_anchor: "Di dalam tulang belakangmu ada cairan bening yang dinamakan cerebrospinal fluid... Ketika tubuh hening dan napas teratur, ritme cairan ini mengalir tenang.",
    reflection_target: "Momen ketika duduk diam tanpa gawai selama beberapa menit ternyata sanggup meredakan kekacauan pikiran yang seharian terasa buntu."
  },
  {
    page_number: 8,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Rahim Gelap Pembersih Racun Saraf",
    subtitle: "Ketika kegelapan mutlak menjadi ruang bagi raga untuk mencuci karat otaknya.",
    side_a_text: "Kelenjar pinealmu hanya mau mencuci racun otak dalam kegelapan mutlak tanpa setitik pun cahaya.",
    visual_concept: "Interior bilik sentong tengah rumah limasan kayu jati kuno dalam kegelapan pekat yang tenang, siluet samar seseorang duduk bersila hening di atas tikar pandan dalam keheningan mutlak tanpa cahaya buatan.",
    image_prompt: "[SUBJECT] Faint silhouette of an Indonesian person seated calmly in cross-legged meditation * [ORDINARY INDONESIAN ENVIRONMENT] traditional windowless inner chamber (sentong tengah) of an ancient Javanese wooden limasan house immersed in deep, pure darkness * [HUMAN ACTION / EMOTION] sitting in profound sensory deprivation, eyes gently closed, experiencing deep somatic rest and cellular restoration * [ONE MEANINGFUL DETAIL] barely perceptible ambient moonlight rim-lighting the edge of a heavy teak wall panel, framing the darkness * [LIGHTING] extreme low-key natural darkness, rich deep charcoal and velvet black shadows * [MATERIAL / TEXTURE] weathered ancient teak grain, woven pandanus mat, darkness as a physical calming medium * [COMPOSITION] vertical 9:16 framing, seated figure centered low in frame, vast quiet darkness overhead * [STYLE] minimalist fine art analog photography, subdued chiaroscuro, organic film grain * [NEGATIVE CONSTRAINTS] no glowing third eye, no purple cosmic energy, no neon light, no digital flare, no text, no watermark",
    source_anchor: "Kelenjar pineal hanya mau membanjiri tubuh dengan melatonin kalau matamu berada dalam kegelapan mutlak... Kegelapan itu rahim pemulihanmu.",
    reflection_target: "Pengalaman merasakan kelegaan mendalam saat berada di ruangan yang benar-benar gelap gulita tanpa gangguan lampu gawai."
  },
  {
    page_number: 9,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Tulang Punggung Sebagai Tiang Antena Batin",
    subtitle: "Menegakkan raga bukan soal postur militer, tapi kejujuran jalur napas.",
    side_a_text: "Kenapa saat hatimu sedang hancur, pundakmu yang pertama kali membungkuk ke depan?",
    visual_concept: "Seorang pemuda duduk di tepi tempat tidur kayu bersahaja, perlahan menarik napas panjang dan menegakkan punggungnya setelah menerima kabar berat.",
    image_prompt: "[SUBJECT] A young Indonesian man seated on the edge of a simple wooden bed * [ORDINARY INDONESIAN ENVIRONMENT] small modest bedroom with bare wooden furniture in soft morning light * [HUMAN ACTION / EMOTION] caught in the subtle motion of un-slumping his shoulders, lifting his chest, taking one deep restorative breath * [ONE MEANINGFUL DETAIL] the morning sunlight tracing a clean, sharp highlight along the ridge of his straight back against the dim wall * [LIGHTING] early morning sun beam cutting horizontally across the room, illuminating dust and fabric * [MATERIAL / TEXTURE] coarse cotton bedsheet, unvarnished wooden bed frame, textured woven bamboo wall * [COMPOSITION] vertical 9:16 orientation, figure positioned in center-lower frame, clean uncluttered space above * [STYLE] realistic intimate photography, poetic restraint, rich warm shadows and natural film grain * [NEGATIVE CONSTRAINTS] no glowing antenna graphics, no electric currents running up spine, no sci-fi effects, no text",
    source_anchor: "Tulang punggungmu adalah tiang penyangga kesadaran... Bila batinmu tertekan, posturmu merosot; bila punggungmu tegak dan rileks, napasmu kembali leluasa.",
    reflection_target: "Pengalaman menyadari bagaimana beban pikiran dan kesedihan langsung mengubah postur tubuh menjadi layu dan sesak napas."
  },
  {
    page_number: 10,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Jagat Alit & Jagat Gedhe",
    subtitle: "Raga adalah alam semesta yang diperkecil; semesta adalah raga yang diperluas.",
    side_a_text: "Bagaimana mungkin keluasan langit malam bisa muat di dalam tempayan sekecil ini?",
    visual_concept: "Sebuah gentong tanah liat berisi air bening di halaman belakang rumah Jawa malam hari, permukaannya memantulkan sepotong langit bertabur bintang tanpa riak.",
    image_prompt: "[SUBJECT] A traditional Indonesian earthenware water jar (gentong tanah liat) filled to the brim with clear calm water * [ORDINARY INDONESIAN ENVIRONMENT] quiet open backyard of a village home beneath a clear night sky * [HUMAN ACTION / EMOTION] no visible human, but intimate human scale; feeling of quiet solitary wonder in the dead of night * [ONE MEANINGFUL DETAIL] the dark water surface perfectly mirror-reflecting the starry night sky and a sliver of dark banana leaf overhead * [LIGHTING] cool deep indigo night sky, faint starlight reflecting sharply on the black water * [MATERIAL / TEXTURE] rough reddish-brown clay texture, smooth water surface, weathered soil surround * [COMPOSITION] vertical 9:16 layout, the jar grounded firmly at bottom, deep expansive dark sky rising above * [STYLE] poetic nocturnal realism, deep velvet blacks, restrained analog grain * [NEGATIVE CONSTRAINTS] no glowing spinal nervous system in the water, no celestial vortex, no surreal fantasy swirls, no text",
    source_anchor: "Nenek moyang kita merumuskannya dalam kearifan Jagat Alit (mikrokosmos raga manusia) dan Jagat Gedhe (makrokosmos alam semesta). Keduanya saling mencerminkan.",
    reflection_target: "Pengalaman memandang benda sederhana di pekarangan malam hari dan mendadak merasa terhubung dengan luasnya alam semesta."
  },
  {
    page_number: 11,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Rongga Kosong Batang Kangkung",
    subtitle: "Kehampaan di dalam batang yang memungkinkannya mengapung dan lentur.",
    side_a_text: "Ternyata yang membuat batang ini tegak mengapung di air bukanlah dagingnya, melainkan ruang kosongnya.",
    visual_concept: "Tangan seseorang memotong batang kangkung di atas talenan kayu di dapur pawon pagi hari; pisau berhenti tepat saat memperlihatkan rongga udara silinder yang bersih di dalam batangnya.",
    image_prompt: "[SUBJECT] Hands of an Indonesian mother or young cook using a small kitchen knife * [ORDINARY INDONESIAN ENVIRONMENT] rustic traditional Javanese kitchen (pawon) in early morning * [HUMAN ACTION / EMOTION] carefully slicing fresh water spinach (kangkung) on a thick cross-section wooden cutting board * [ONE MEANINGFUL DETAIL] a freshly cut stalk revealing its clean hollow cylindrical chamber, glistening with tiny natural moisture drops * [LIGHTING] gentle morning sun streaming through kitchen window, highlighting the fresh green and wood grain * [MATERIAL / TEXTURE] wet wooden chopping board, crisp green vegetable fibers, dull steel knife blade * [COMPOSITION] vertical 9:16 macro editorial shot, focused on hands and vegetable in lower-mid frame, quiet shadowy kitchen background above * [STYLE] warm organic food and lifestyle documentary, rich tactile textures, filmic color grading * [NEGATIVE CONSTRAINTS] no flying egrets, no floating feathers, no symbolic energy diagrams, no fantasy light beams, no text",
    source_anchor: "Leluhur kita memakai sanepan batang kangkung... Di tengahnya ada rongga kosong. Karena rongga hampa itulah ia lentur dihempas arus dan tetap mengapung.",
    reflection_target: "Pengalaman menyadari bahwa hati yang terlalu penuh dengan kecemasan dan prasangka justru gampang patah saat diterpa masalah."
  },
  {
    page_number: 12,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Tegaknya Tubuh Menghadap Semesta",
    subtitle: "Berdiri tegak bukan untuk menantang langit, tapi menyatukan bumi dan surga.",
    side_a_text: "Ada ketenangan aneh saat punggungmu akhirnya berhenti bersandar dan belajar menopang dirinya sendiri.",
    visual_concept: "Seseorang duduk bersila di lantai pendopo kayu tua. Di belakangnya, agak berjarak, berdiri tiang jati lawas, keduanya secara alami berbagi garis vertikal yang sama.",
    image_prompt: "[SUBJECT] A contemplative Indonesian person sitting cross-legged on polished floorboards * [ORDINARY INDONESIAN ENVIRONMENT] open wooden pendopo pavilion of an old Javanese estate * [HUMAN ACTION / EMOTION] sitting quietly erect without rigid tension, facing the quiet misty garden * [ONE MEANINGFUL DETAIL] a massive weathered solid teak wooden pillar standing steadily a few paces behind them, naturally mirroring the vertical poise of their spine * [LIGHTING] calm overcast daylight, soft diffused highlights along the wood grain and cotton clothing * [MATERIAL / TEXTURE] aged dark teak pillars, smooth polished floor, soft unbleached cotton * [COMPOSITION] vertical 9:16 framing, vertical harmony between human posture and timber pillar, spacious upper negative space * [STYLE] serene architectural and human editorial photography, muted earth tones, 35mm grain * [NEGATIVE CONSTRAINTS] no glowing skeletal alignment lines, no laser beams, no mystical chakra drawings, no CGI, no text",
    source_anchor: "Ketika kamu duduk tegak dengan rileks, ragamu menghubungkan tarikan gravitasi bumi di bawah dengan lapangnya langit di atas.",
    reflection_target: "Momen ketika memutuskan berhenti mengeluh dan mulai duduk tegak memikul tanggung jawab hidupnya sendiri."
  },
  {
    page_number: 13,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Tidur Gelap & Malam yang Mengobati",
    subtitle: "Ketika lampu dipadamkan, raga memulai pembersihan terdalamnya.",
    side_a_text: "Lampu kamar sudah padam, tapi layarmu masih membakar mata sejengkal dari hidung.",
    visual_concept: "Sebuah ponsel terbalik dalam keadaan layar padam di atas meja kayu samping kasur, di kamar tidur bersahaja yang gelap pekat.",
    image_prompt: "[SUBJECT] A modest Indonesian bedroom bedside scene at night * [ORDINARY INDONESIAN ENVIRONMENT] simple wooden bedside table next to a rustic mattress in a darkened room * [HUMAN ACTION / EMOTION] a person lying peacefully under a dark blanket in the background, breathing steadily in total darkness * [ONE MEANINGFUL DETAIL] a modern smartphone placed screen-down, completely dark and silent, beside a simple brass drinking cup * [LIGHTING] deep natural darkness with very soft, faint blue night ambience entering from a curtain gap * [MATERIAL / TEXTURE] matte plastic phone back, rough unvarnished wood, soft dark cotton blanket, deep shadow gradients * [COMPOSITION] vertical 9:16 layout, table and phone in lower foreground, dark serene bedroom atmosphere filling the frame * [STYLE] quiet atmospheric photography, heavy deep charcoal blacks, film grain, zero digital noise * [NEGATIVE CONSTRAINTS] no glowing pineal gland, no blue digital rays piercing skull, no floating brain graphics, no text",
    source_anchor: "Saat kegelapan total tiba, tubuh memproduksi hormon melatonin dan mengalirkan pembersihan saraf... Jangan curi waktu pemulihan ragamu dengan radiasi layar.",
    reflection_target: "Pengalaman merasa lelah sepanjang hari hanya karena kebiasaan scrolling ponsel di kamar gelap menjelang tidur."
  },
  {
    page_number: 14,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Jeda Tiga Detik Sebelum Merespons",
    subtitle: "Memutus rantai karma lama tepat di persimpangan amarah.",
    side_a_text: "Saat kata-kata pedas itu datang, bisakah kamu diam tiga detik sebelum membalasnya?",
    visual_concept: "Seorang pengendara motor membuka kaca helm di tengah kemacetan lampu merah sore yang padat, menarik napas dalam tanpa membunyikan klakson.",
    image_prompt: "[SUBJECT] An Indonesian motorcycle commuter in his late 20s wearing a helmet with visor pushed up * [ORDINARY INDONESIAN ENVIRONMENT] crowded urban traffic intersection in Yogyakarta during humid evening dusk * [HUMAN ACTION / EMOTION] taking a slow, conscious breath with relaxed facial muscles, choosing calmness amid chaos instead of pressing the horn * [ONE MEANINGFUL DETAIL] his hand resting lightly on the motorcycle handlebar grip without squeezing the brake or throttle tightly * [LIGHTING] warm red glow of traffic tail lights mixed with dim twilight sky and soft motorcycle headlights * [MATERIAL / TEXTURE] asphalt road, wet motorcycle mirrors, worn jacket fabric, evening mist * [COMPOSITION] vertical 9:16 frame, rider's calm face centered in mid-ground, blurred sea of city traffic in background * [STYLE] authentic street documentary style, cinematic color contrast, gritty fine grain * [NEGATIVE CONSTRAINTS] no countdown timer graphics, no brain synapses illustration, no glowing heart shield, no text",
    source_anchor: "Antara stimulus yang memancing emosi dan reaksimu, selalu ada celah jeda tiga detik. Di dalam jeda itulah letak kebebasan dan takdir barumu.",
    reflection_target: "Momen ketika berhasil menahan diri tidak membalas amarah seseorang, dan merasakan kelegaan karena tidak memperpanjang masalah."
  },
  {
    page_number: 15,
    chapter_code: "BAB 01",
    chapter_name: "Anatomi Tubuh Energi & Memori Karma",
    title: "Tak Ada yang Perlu Dicari ke Luar",
    subtitle: "Kuil terindah yang pernah diciptakan semesta adalah raga yang kau bawa hari ini.",
    side_a_text: "Tempelkan tanganmu di dada. Berhentilah mencari ke luar; kuil sucimu bernapas di sana.",
    visual_concept: "Seseorang berdiri di teras rumah kampung Jawa saat fajar, meletakkan tangan kanannya di tengah dada sembari memandang kabut tipis di pekarangan.",
    image_prompt: "[SUBJECT] An Indonesian person in simple earthy linen attire seen from side angle * [ORDINARY INDONESIAN ENVIRONMENT] open wooden veranda of a village home at early morning * [HUMAN ACTION / EMOTION] placing their right hand flat against the center of their chest, eyes calmly half-closed, feeling their own heartbeat * [ONE MEANINGFUL DETAIL] morning mist gently clearing across the modest front yard, revealing wet grass and stone pathway * [LIGHTING] pale pearl-grey morning twilight gradually warming into subtle golden sunrise * [MATERIAL / TEXTURE] weathered wood floor, damp garden stones, coarse linen cloth, dewy foliage * [COMPOSITION] vertical 9:16 layout, serene figure anchored in lower half, broad calm morning mist filling the top * [STYLE] deeply peaceful cinematic photography, muted earth tones, soft highlights, analog 35mm grain * [NEGATIVE CONSTRAINTS] no temple graphics super-imposed on chest, no glowing golden buddha, no floating symbols, no CGI, no text",
    source_anchor: "Seluruh pencarian spiritualmu akan berujung pada satu kesadaran bersahaja: raga ini kuil sucimu. Jaga dan dengarkan dia sebelum kamu melangkah menata nasib.",
    reflection_target: "Momen kepulangan batin ketika menyadari bahwa ketenangan sejati tidak ada di tempat yang jauh, melainkan di dalam helaan napas sendiri."
  }
];
