module.exports = [
  {
    page_number: 16,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    subtitle: "Mengubah Pola Batin Bawah Sadar Sebelum Menata Nasib Lahir",
    side_a_text: "Mulutmu minta rezeki melimpah, tapi dadamu seharian gemetar takut miskin. Kira-kira yang mana yang didengar semesta?",
    visual_concept: "Seorang pemuda duduk sendirian di meja kayu warkop Kaliurang saat senja gerimis, secangkir kopi hitam mengepul di depannya dengan pantulan jendela kaca basah.",
    image_prompt: "[SUBJECT] An introspective Indonesian man in his late 20s wearing a simple olive cotton shirt * [ORDINARY INDONESIAN ENVIRONMENT] roadside coffee shop in Kaliurang, Yogyakarta during misty twilight drizzle * [HUMAN ACTION / EMOTION] sitting alone at a rough wooden table, holding a hot glass cup with both hands, staring out the window with quiet honesty * [ONE MEANINGFUL DETAIL] condensation droplets trickling down the glass window, blurring the headlights of passing motorbikes outside * [LIGHTING] warm amber low-hanging pendant light mixed with the cool blue mist of dusk * [MATERIAL / TEXTURE] wet window pane, rough unvarnished wood table, ceramic saucer, textured cotton * [COMPOSITION] vertical 9:16 portrait format, subject positioned in lower half, broad calm reflective glass area above * [STYLE] atmospheric Indonesian indie cinema still, analog 35mm grain, deep shadows, muted earth tones * [NEGATIVE CONSTRAINTS] no glowing brain graphics, no floating money or numbers, no futuristic holograms, no text, no watermark",
    source_anchor: "Pikiran bawah sadar bekerja berdasarkan rasa dominan yang kamu pendam di dada, bukan sekadar kata-kata manis di bibir saat kamu berdoa.",
    reflection_target: "Pengalaman menyadari kontradiksi antara doa yang diucapkan mulut dengan ketakutan finansial yang terus menggerogoti dada."
  },
  {
    page_number: 17,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Asbak Penuh & Kawan yang Tersesat",
    subtitle: "Ketika seluruh seminar sukses tak mampu membungkam kegelisahan di dada.",
    side_a_text: "Pernahkah kamu ikut semua seminar sukses, tapi pulang ke rumah tetap dikejar rasa cemas yang sama?",
    visual_concept: "Dua pria duduk berhadapan di warung kopi larut malam Yogya, asbak seng penuh puntung kretek di antara mereka, terdiam setelah kehabisan teori sukses.",
    image_prompt: "[SUBJECT] Two Indonesian men in their early 30s seated across a worn wooden table * [ORDINARY INDONESIAN ENVIRONMENT] dimly lit traditional Yogyakarta warkop past midnight * [HUMAN ACTION / EMOTION] leaning back, quiet and contemplative, exhaustion mixed with genuine vulnerability, having run out of superficial conversation * [ONE MEANINGFUL DETAIL] an old pressed-tin ashtray overflowing with extinguished clove cigarette butts, a faint solitary wisp of smoke rising from the last one * [LIGHTING] solitary bare fluorescent tube muted by warm yellow paper shade, casting heavy soft shadows * [MATERIAL / TEXTURE] worn painted wood, oxidized tin ashtray, glass cups with coffee dregs, fabric wrinkles * [COMPOSITION] vertical 9:16 layout, the table and ashtray anchored at bottom, the men in mid-frame, dark ceiling above * [STYLE] gritty documentary photography, authentic Indonesian night mood, 35mm grain * [NEGATIVE CONSTRAINTS] no motivational banners, no glowing symbols, no fantasy effects, no text, no watermark",
    source_anchor: "Banyak orang menghabiskan jutaan rupiah untuk seminar motivasi, tapi begitu pulang ke kamar tidurnya, program bawah sadar lamanya kembali memegang kendali.",
    reflection_target: "Pengalaman merasa hampa dan tetap cemas meskipun sudah membaca buku motivasi atau mengikuti pelatihan pengembangan diri."
  },
  {
    page_number: 18,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Pintu Kesadaran Dimulai Saat Semuanya Runtuh",
    subtitle: "Saat benteng egomu hancur, barulah benih kesadaran sejati bisa bertunas.",
    side_a_text: "Saat hidupmu remuk, kamu tidak butuh diceramahi dalil; ragamu cuma butuh tidur dalam gelap tanpa ketakutan.",
    visual_concept: "Seseorang duduk lemas bersandar pada pilar joglo tua di beranda belakang rumah saat tengah malam, cangkir tanah liat kosong tergeletak di sampingnya.",
    image_prompt: "[SUBJECT] An Indonesian man sitting slouched on the floorboards with his back against an old timber column * [ORDINARY INDONESIAN ENVIRONMENT] quiet rear veranda of a traditional Javanese village house at late night * [HUMAN ACTION / EMOTION] head tilted back, hands resting limp beside his legs, complete surrender after overwhelming emotional exhaustion * [ONE MEANINGFUL DETAIL] a cracked terracotta cup resting on the cool clay tiles beside his bare foot * [LIGHTING] faint blue moonlight illuminating the edge of the roof eaves, interior plunged in deep charcoal shadows * [MATERIAL / TEXTURE] weathered ancient teak column, cracked terracotta tiles, coarse fabric, cool air * [COMPOSITION] vertical 9:16 frame, figure grounded in lower third, deep empty darkness rising upwards * [STYLE] contemplative neo-realist cinema, restrained exposure, rich filmic grain * [NEGATIVE CONSTRAINTS] no glowing angel wings, no dramatic tears of light, no shattered glass CGI, no text",
    source_anchor: "Titik balik spiritual sejati hampir selalu diawali oleh keruntuhan ego. Saat kamu tidak lagi bisa berpura-pura kuat, saat itulah pikiran bawah sadar siap menerima pembaruan.",
    reflection_target: "Momen ketika titik terendah hidup justru menjadi ruang paling hening tempat kamu berhenti membual pada diri sendiri."
  },
  {
    page_number: 19,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Penjaga Pintu yang Keras Kepala",
    subtitle: "Critical faculty di kepalamu selalu menolak kalimat yang tak diyakini dadamu.",
    side_a_text: "Berapa kali kamu memaksakan senyum di depan cermin, tapi suara kecil di kepalamu tetap membisikkan kebohongan?",
    visual_concept: "Seorang wanita atau pria berdiri di depan cermin antik wastafel kamar mandi tua, menatap bayangan wajahnya sendiri dengan tatapan jujur tanpa topeng.",
    image_prompt: "[SUBJECT] An Indonesian person in simple home clothes standing before a mirror * [ORDINARY INDONESIAN ENVIRONMENT] vintage bathroom with weathered green ceramic tiles and an old wooden-framed mirror * [HUMAN ACTION / EMOTION] hands resting on the edge of the washbasin, looking directly into their own eyes in the glass with quiet, unsparing honesty * [ONE MEANINGFUL DETAIL] the mirror's silvering slightly aged with dark flecks around the rim, framing a face stripped of all social masks * [LIGHTING] weak warm incandescent bulb beside the mirror casting honest, gentle facial shadows * [MATERIAL / TEXTURE] crazed ceramic glaze, tarnished mirror glass, water droplets on porcelain, cotton shirt * [COMPOSITION] vertical 9:16 framing, subject and mirror centered, uncluttered dark upper wall * [STYLE] intimate psychological realism, 35mm film aesthetic, muted vintage tones * [NEGATIVE CONSTRAINTS] no glowing second persona in mirror, no spooky monsters, no floating brain neurons, no text",
    source_anchor: "Otak sadarmu punya satpam yang disebut critical faculty. Kalau kamu cuma mengulang afirmasi positif tanpa getaran rasa di dada, satpam itu akan langsung membuangnya.",
    reflection_target: "Pengalaman mengucapkan kata-kata positif pada diri sendiri namun batin kecil di dalam langsung menyanggahnya karena tahu itu palsu."
  },
  {
    page_number: 20,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Kamu Wayang Sekaligus Dalangnya",
    subtitle: "Menyadari bahwa lakon yang kau keluhkan setiap hari adalah naskah yang kau setujui sendiri.",
    side_a_text: "Kalau kamu terus menyalahkan takdir atas hidupmu, lantas siapa sebenarnya yang memegang tali di belakang layarmu?",
    visual_concept: "Di balik kelir putih pendopo pertunjukan wayang malam hari, tangan seorang dalang memegang tangkai wayang kulit, siluet wayang dan tangan sang dalang tampak dalam satu berkas lampu blencong.",
    image_prompt: "[SUBJECT] Silhouette of an Indonesian puppeteer (dalang)'s weathered hands holding the horn handle of a leather wayang puppet * [ORDINARY INDONESIAN ENVIRONMENT] behind the white cotton screen (kelir) in an old village pendopo pavilion * [HUMAN ACTION / EMOTION] adjusting the puppet poised against the taut cloth, focused calm artistic command * [ONE MEANINGFUL DETAIL] the traditional oil lamp (blencong) casting a warm flicker that outlines the intricate punched-leather holes of the puppet * [LIGHTING] dramatic chiaroscuro, warm yellow flickering firelight against the translucent off-white screen, deep surrounding darkness * [MATERIAL / TEXTURE] carved water buffalo hide, hand-spun cotton screen, smoky soot on lamp brass * [COMPOSITION] vertical 9:16 composition, the puppet and controlling hand positioned at center-lower, vast white shadow-screen above * [STYLE] classical Nusantara fine art photography, cinematic contrast, analog grain * [NEGATIVE CONSTRAINTS] no cosmic puppets in space, no laser light strings, no CGI marionette strings, no text",
    source_anchor: "Dalam filsafat wayang purwa, kamu sering merasa sebagai wayang yang dimainkan takdir. Tapi begitu kesadaranmu bangun, kamu menyadari bahwa kamu jugalah yang sedang memegang cempurit di balik kelir.",
    reflection_target: "Pengalaman mendadak sadar bahwa keputusan-keputusan kecil dan pembiaran diri di masa lalulah yang menciptakan situasi sulit hari ini."
  },
  {
    page_number: 21,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Lima Belas Menit Menjelang Lelap dan Bangun",
    subtitle: "Dua jendela emas tempat gerbang pikiran bawah sadar terbuka lebar tanpa penjaga.",
    side_a_text: "Layar ponselmu adalah hal terakhir yang kamu tatap sebelum lelap, lalu kamu heran kenapa bangun tidur selalu gelisah?",
    visual_concept: "Kamar tidur bersahaja saat fajar mulai merekah, ponsel terbalik di meja kayu samping ranjang, sementara seseorang mulai membuka mata dengan tenang.",
    image_prompt: "[SUBJECT] An Indonesian person waking gently in a modest bedroom * [ORDINARY INDONESIAN ENVIRONMENT] bedroom with whitewashed wooden walls and a simple cotton mattress * [HUMAN ACTION / EMOTION] lying still under a thin blanket, eyes softly opening to look at the ceiling without rushing to grab a phone * [ONE MEANINGFUL DETAIL] a phone resting face-down on a small wooden side table, completely dormant in the morning shadow * [LIGHTING] pale blue and silver twilight of dawn filtering through a sheer window curtain * [MATERIAL / TEXTURE] soft woven cotton blanket, grain of unpainted timber, morning stillness * [COMPOSITION] vertical 9:16 portrait orientation, peaceful figure in lower frame, tranquil ambient room space rising above * [STYLE] quiet atmospheric realism, low-contrast natural morning palette, subtle grain * [NEGATIVE CONSTRAINTS] no alarm clock graphics, no digital waves floating from phone, no glowing hypnotic swirls, no text",
    source_anchor: "Gelombang otakmu turun ke frekuensi theta tepat sebelum tidur dan sesaat setelah bangun. Apa pun kesan rasa yang kamu masukkan di lima belas menit itu akan dicetak menjadi nasib.",
    reflection_target: "Pengalaman bangun tidur dengan rasa cemas atau kesal karena membaca berita atau media sosial sesaat sebelum tidur malam sebelumnya."
  },
  {
    page_number: 22,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Keheningan yang Hilang di Balik Pintu Kamar Mandi",
    subtitle: "Bahkan ruang paling pribadi pun kita serahkan pada kebisingan layar.",
    side_a_text: "Bahkan di bilik toilet yang hening, kamu tak sanggup berduaan dengan kepalamu sendiri tanpa menyalakan layar.",
    visual_concept: "Seseorang duduk termenung di kamar mandi bersahaja berlantai semen bersih, kedua tangan bertumpu di lutut tanpa memegang gawai, seberkas sinar pagi menembus roster bata.",
    image_prompt: "[SUBJECT] An Indonesian man sitting quietly in contemplative solitude * [ORDINARY INDONESIAN ENVIRONMENT] clean, modest Indonesian bathroom with grey cement floor and a terracotta water vat (bak mandi) * [HUMAN ACTION / EMOTION] resting his forearms on his knees, head slightly bowed, completely present in the quiet moment with empty hands * [ONE MEANINGFUL DETAIL] a beam of morning sunlight cutting diagonally through terracotta vent blocks (roster), illuminating dust motes in the moist air * [LIGHTING] high-contrast morning shaft of light cutting across damp cool concrete * [MATERIAL / TEXTURE] smooth wet cement, porous terracotta brick, still water in the vat, plastic water dipper (gayung) * [COMPOSITION] vertical 9:16 layout, subject grounded in lower half, geometric light patterns and roster wall in upper frame * [STYLE] unvarnished slice-of-life realism, moody documentary aesthetic, 35mm grain * [NEGATIVE CONSTRAINTS] no dirty or gross elements, no smartphone in hand, no glowing virtual feeds, no text, no watermark",
    source_anchor: "Kita kehilangan ruang-ruang mikro tempat pikiran bawah sadar memproses sampah hariannya. Kita takut pada keheningan karena di sana suara batin yang jujur mulai terdengar.",
    reflection_target: "Pengalaman menyadari kecanduan gawai yang begitu parah hingga beberapa menit di kamar mandi saja terasa hampa tanpa menatap layar."
  },
  {
    page_number: 23,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Kutukan Ibu yang Menembus Langit",
    subtitle: "Daya getar kata-kata yang diucapkan dari kedalaman rasa tanpa sandiwara.",
    side_a_text: "Saat amarahmu meledak, apakah sumpah serapah yang keluar dari mulutmu, atau doa yang menembus langit?",
    visual_concept: "Seorang ibu paruh baya Jawa berdiri di samping tungku luweng di dapur tradisional, menatap kayu bakar yang menyala dengan raut wajah hening menahan gejolak rasa.",
    image_prompt: "[SUBJECT] A middle-aged Javanese mother wearing a traditional batik sarong and faded cotton kebaya * [ORDINARY INDONESIAN ENVIRONMENT] rustic earth-floored village kitchen (pawon) beside an earthen hearth (luweng) * [HUMAN ACTION / EMOTION] pausing while tending the fire, holding a bamboo blowing pipe (semprong), her face a study in deep emotional restraint and silent prayer * [ONE MEANINGFUL DETAIL] red and orange embers glowing inside the clay hearth, casting warm light on her weathered hands * [LIGHTING] warm intense fireplace glow illuminating the lower figure against the dark smoke-stained kitchen walls * [MATERIAL / TEXTURE] packed dirt floor, soot-stained timber, terracotta pots, glowing wood charcoal * [COMPOSITION] vertical 9:16 frame, mother and hearth grounded in lower two-thirds, rising dark smoke and rafters above * [STYLE] intimate culturally rooted photography, rich shadow depth, cinematic grain * [NEGATIVE CONSTRAINTS] no curses flying as red lightning, no supernatural smoke spirits, no melodrama, no text",
    source_anchor: "Kata-kata seorang ibu memiliki daya getar dahsyat karena meluncur dari ulu hati yang terhubung langsung dengan rahim kehidupan. Begitu pula setiap ucapanmu saat batinmu terdesak.",
    reflection_target: "Pengalaman mengingat ucapan emosional yang pernah dilontarkan kepada orang terdekat dan menyadari dampak batin jangka panjangnya."
  },
  {
    page_number: 24,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Tujuh Puluh Dua Persen Wadah Cairan",
    subtitle: "Raga adalah wadah air yang menyerap setiap getaran suara dan prasangka.",
    side_a_text: "Tubuhmu tujuh puluh persen air; kata-kata apa yang setiap hari kamu bisikkan ke dalam darahmu sendiri?",
    visual_concept: "Tangan seseorang menuangkan air bening dari kendi gerabah Kasongan ke dalam mangkuk tanah liat di beranda kayu yang sejuk.",
    image_prompt: "[SUBJECT] Hands of an Indonesian person pouring water from a traditional clay pitcher (kendi) * [ORDINARY INDONESIAN ENVIRONMENT] shaded wooden veranda surrounded by lush tropical green foliage * [HUMAN ACTION / EMOTION] pouring unhurriedly with steady attention, watching the smooth clear stream fill the clay bowl * [ONE MEANINGFUL DETAIL] a clean continuous arc of clear water catching the morning light, tiny droplets splashing softly into the earthenware vessel * [LIGHTING] soft diffused daylight filtering through garden leaves, dappled gentle illumination * [MATERIAL / TEXTURE] porous terracotta clay, smooth liquid stream, dark weathered wood table * [COMPOSITION] vertical 9:16 close-up framing, water vessel and hands centered, quiet green garden bokeh above * [STYLE] serene mindful photography, organic textures, tactile 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing water crystals, no frozen molecular science diagrams, no new-age blue halos, no text",
    source_anchor: "Sebagian besar ragamu adalah cairan. Air memiliki sifat menyerap dan menyimpan frekuensi informasi. Setiap kali kamu memaki diri sendiri di dalam hati, cairan sel tubuhmu ikut keruh.",
    reflection_target: "Pengalaman menyadari kebiasaan mengutuk atau mencela kekurangan diri sendiri dalam hati setiap kali melakukan kesalahan sepele."
  },
  {
    page_number: 25,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Ritual Bersahaja Penembus Keraguan",
    subtitle: "Bukan kemewahan mantranya, melainkan kepolosan keyakinan seorang anak kecil.",
    side_a_text: "Waktu kecil kamu percaya seratus persen ucapan bapakmu; kapan tepatnya keraguan mulai meracuni doamu?",
    visual_concept: "Seorang anak laki-laki duduk di tepi jalan kampung memegang dompet kulit usang bapaknya yang kosong, menatap mobil pengantin melintas di kejauhan dengan mata polos penuh harap.",
    image_prompt: "[SUBJECT] A small Indonesian village boy aged around 7 in simple shorts and faded t-shirt * [ORDINARY INDONESIAN ENVIRONMENT] grassy roadside of a quiet rural village lane in Java * [HUMAN ACTION / EMOTION] sitting on a curb, holding a worn brown leather wallet between his hands, looking into the distance with innocent, pure faith * [ONE MEANINGFUL DETAIL] an old, empty leather wallet held with two hands as if it were the most sacred treasure * [LIGHTING] golden hour late afternoon sunlight warming the boy's face and dust on the road * [MATERIAL / TEXTURE] weathered cracked leather, dusty earth, coarse cotton clothes, dry grass blades * [COMPOSITION] vertical 9:16 layout, the boy seated in lower third, long rural road stretching into the soft blurred horizon above * [STYLE] nostalgic storytelling photography, warm vintage grading, gentle film grain * [NEGATIVE CONSTRAINTS] no money raining from sky, no golden light beams from wallet, no sentimental greeting card kitsch, no text",
    source_anchor: "Pikiran bawah sadar hanya merespons kepasrahan yang polos tanpa kalkulasi logika. Semakin banyak keraguan dan perhitungan untung-rugi di kepalamu, semakin tebal sekat doamu.",
    reflection_target: "Pengalaman mengingat masa kanak-kanak saat mempercayai sesuatu dengan keyakinan penuh tanpa kecemasan analitis orang dewasa."
  },
  {
    page_number: 26,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Zikir yang Menggetarkan Ulu Hati",
    subtitle: "Mengembalikan pengulangan kata dari sekadar hafalan bibir menjadi denyut raga.",
    side_a_text: "Bibirmu melafalkan ribuan wirid secara mekanis, tapi pernahkah kamu berbisik jujur memakai bahasa ibumu?",
    visual_concept: "Seseorang bersimpuh di langgar desa tua di atas tikar pandan yang wangi, menangkupkan kedua tangan di dada dalam bisikan lirih yang hening.",
    image_prompt: "[SUBJECT] An Indonesian man kneeling quietly in solitude on a woven pandan mat * [ORDINARY INDONESIAN ENVIRONMENT] interior of a small wooden village prayer room (langgar) at dusk * [HUMAN ACTION / EMOTION] hands gently cupped near his heart, eyes closed, lips barely parted in a soft, sincere whisper of unpolished vernacular prayer * [ONE MEANINGFUL DETAIL] worn wooden prayer beads (tasbih) resting gently in his lap on the straw mat * [LIGHTING] dim twilight entering open wooden windows, single warm kerosene lantern casting a soft golden glow on his face * [MATERIAL / TEXTURE] woven pandanus straw, aged teak timber, worn cotton sarong, warm lantern glass * [COMPOSITION] vertical 9:16 portrait orientation, worshipper centered in lower frame, tranquil shadowy wooden rafters above * [STYLE] deeply spiritual documentary realism, muted earthy tones, authentic film grain * [NEGATIVE CONSTRAINTS] no golden glowing rays bursting from chest, no floating Arabic letters, no mystical fog, no text",
    source_anchor: "Pengulangan mantra atau wirid baru memiliki daya tembus ke alam bawah sadar saat ia berhenti menjadi rutinitas mekanis dan bergetar menjadi bahasa kejujuran jiwa.",
    reflection_target: "Pengalaman beribadah secara terburu-buru seperti menggugurkan kewajiban tanpa pernah benar-benar mengadu dengan jujur kepada Sang Pencipta."
  },
  {
    page_number: 27,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Perang Sengkuni Melawan Semar di Dadamu",
    subtitle: "Dialektika abadi antara suara licik yang selalu curiga dan kebijaksanaan yang mengayomi.",
    side_a_text: "Di kepalamu ada suara yang selalu curiga, dan di dadamu ada rasa yang menatap dunia dengan teduh.",
    visual_concept: "Seorang pengrajin kayu duduk di beranda bengkelnya, memegang dua pahatan wayang kulit yang belum selesai: profil berhidung tajam dan profil bersenyum bulat bersahaja.",
    image_prompt: "[SUBJECT] An experienced Indonesian craftsman sitting on a wooden stool in his open-air workshop * [ORDINARY INDONESIAN ENVIRONMENT] woodcarver's workshop in rural Java surrounded by shavings and tools * [HUMAN ACTION / EMOTION] looking thoughtfully at two unfinished carved puppet figures held in his hands, quiet contemplation of human character * [ONE MEANINGFUL DETAIL] two distinct puppet profiles: one with sharp angular features and another with a round serene smile, caught in natural wood tones * [LIGHTING] soft side lighting from the cloudy afternoon sky, highlighting wood grain and craftsman's weathered face * [MATERIAL / TEXTURE] teak wood curls, steel chisels, textured worktable, faded denim apron * [COMPOSITION] vertical 9:16 layout, craftsman and worktable in lower half, rustic workshop background with negative space above * [STYLE] authentic cultural editorial photography, warm natural colors, tactile 35mm film grain * [NEGATIVE CONSTRAINTS] no devil vs angel wings, no glowing comic book aura, no fantasy battlefield in clouds, no text",
    source_anchor: "Di dalam batin setiap manusia berlangsung perang abadi antara watak Sengkuni (pikiran yang selalu cemas, iri, dan manipulatif) melawan watak Semar (kebijaksanaan rasa yang sabar dan welas asih).",
    reflection_target: "Pengalaman menyadari saat suara ego mulai menghasut untuk berprasangka buruk pada orang lain, sementara hati nurani sebenarnya ingin memaklumi."
  },
  {
    page_number: 28,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Menyambut Fajar Tanpa Racun Medsos",
    subtitle: "Menjaga kesucian pikiran bawah sadar saat hari baru pertama kali disemai.",
    side_a_text: "Belum juga kakimu menyentuh lantai dingin di waktu fajar, jemarimu sudah sibuk memungut keributan dunia luar.",
    visual_concept: "Seseorang duduk di tepi ranjang memegang mug seng enamel berisi air hangat, memandang fajar biru perak melalui jendela terbuka tanpa sentuhan gawai.",
    image_prompt: "[SUBJECT] An Indonesian person in comfortable morning loungewear sitting on the edge of a bed * [ORDINARY INDONESIAN ENVIRONMENT] simple village bedroom with an open window facing morning trees * [HUMAN ACTION / EMOTION] holding a vintage enamel tin mug with both hands, taking a quiet sip while gazing out at the pale dawn horizon * [ONE MEANINGFUL DETAIL] clean morning air blowing the sheer window curtain gently inward, untouched wooden bedside table * [LIGHTING] cool silver-blue morning light breaking through tree branches, gentle ambient illumination * [MATERIAL / TEXTURE] chipped enamel tin mug, soft cotton clothing, cool breeze on skin, wooden window sill * [COMPOSITION] vertical 9:16 frame, person sitting quietly at center, calm luminous dawn sky occupying upper frame * [STYLE] serene lifestyle documentary, minimalist color palette, natural 35mm grain * [NEGATIVE CONSTRAINTS] no social media icons floating in air, no toxic digital slime, no glowing phone, no text",
    source_anchor: "Jika kesan pertama yang kau suapkan ke dalam pikiran bawah sadarmu di pagi hari adalah amarah di media sosial, maka sepanjang hari ragamu akan memproduksi hormon stres.",
    reflection_target: "Pengalaman memulai hari dengan suasana hati yang langsung rusak hanya karena membuka kolom komentar medsos saat baru bangun tidur."
  },
  {
    page_number: 29,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Memutus Rantai Otomatis di Otak Depan",
    subtitle: "Mengambil alih kemudi dari program bawah sadar yang bertindak membabi buta.",
    side_a_text: "Antara hinaan orang lain dan amarahmu yang meledak, ada ruang tiga detik yang menentukan nasibmu.",
    visual_concept: "Seseorang berdiri di pintu rumah memegang gagang pintu, berhenti sejenak sebelum melangkah keluar menghadapi dunia yang bising.",
    image_prompt: "[SUBJECT] An Indonesian man standing in the doorway of his home preparing to leave * [ORDINARY INDONESIAN ENVIRONMENT] front entrance of an ordinary modest Indonesian family home * [HUMAN ACTION / EMOTION] hand resting on the brass doorknob, taking a deep centering breath, calming his face before opening the door * [ONE MEANINGFUL DETAIL] his shoes neatly placed side-by-side on the concrete step, waiting for the deliberate next move * [LIGHTING] soft interior house light behind him contrasting with the bright outdoor morning daylight beyond the window * [MATERIAL / TEXTURE] painted wooden door frame, polished brass knob, cool cement floor, everyday clothes * [COMPOSITION] vertical 9:16 portrait framing, subject centered in vertical door frame, quiet breathing space around * [STYLE] thoughtful observational photography, realistic lighting, fine 35mm film grain * [NEGATIVE CONSTRAINTS] no broken metal chains floating in air, no digital brain synapses, no superhero energy shield, no text",
    source_anchor: "Sebagian besar hidup kita dijalankan secara otomatis oleh program lama di otak belakang. Begitu kamu menghadirkan kesadaran penuh di jeda sesaat, program otomatis itu langsung runtuh.",
    reflection_target: "Momen ketika berhasil menahan diri untuk tidak membalas provokasi orang lain, dan menyadari betapa kuatnya kendali diri dalam hening."
  },
  {
    page_number: 30,
    chapter_code: "BAB 02",
    chapter_name: "Meretas Pikiran Bawah Sadar & Reprogramming Nasib",
    title: "Memegang Sendiri Kendali Layar Batin",
    subtitle: "Bukan dunia luar yang harus kau ubah; jernihkan proyektor rasa di dalam dadamu.",
    side_a_text: "Berhentilah pontang-panting mengejar nasib; jernihkan rasa di dadamu, maka layar dunia di luar akan berganti dengan sendirinya.",
    visual_concept: "Seseorang duduk tenang di amben joglo menatap pelataran batu basah pasca gerimis senja, genangan air tenang memantulkan bintang pertama fajar senja.",
    image_prompt: "[SUBJECT] An Indonesian person sitting in relaxed cross-legged posture on a broad wooden daybed (amben) * [ORDINARY INDONESIAN ENVIRONMENT] open veranda of a traditional Javanese joglo house overlooking a stone courtyard * [HUMAN ACTION / EMOTION] resting hands comfortably in lap, gazing out into the twilight with a settled, deep inner ease * [ONE MEANINGFUL DETAIL] a clean puddle of rainwater on the courtyard stones reflecting the faint first evening star * [LIGHTING] deep twilight blue hour, soft warm amber glow spilling from the inner joglo doorway * [MATERIAL / TEXTURE] wide solid teak planks, wet river stones, damp evening air, smooth cotton fabric * [COMPOSITION] vertical 9:16 layout, figure calmly grounded on the wooden platform, serene dusky sky rising above * [STYLE] quiet contemplative cinematography, rich deep shadows, authentic film grain * [NEGATIVE CONSTRAINTS] no glowing projector beams, no movie screen floating in sky, no cosmic sparkles, no text, no watermark",
    source_anchor: "Dunia di luarmu hanyalah layar bioskop yang memproyeksikan apa yang sedang diputar oleh proyektor rasa di batinmu. Ubah kaset di dalam, maka gambar di luar akan berganti.",
    reflection_target: "Pengalaman menyadari bahwa saat hati damai dan bersyukur, lingkungan sekitar yang tadinya terasa menyebalkan mendadak terasa bersahabat."
  }
];
