module.exports = [
  {
    page_number: 31,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    subtitle: "Menyelaraskan Pabrik Kimia Tubuh Lewat Tirakat yang Membumi",
    side_a_text: "Kamu menuntut batinmu tenang, tapi ragamu kau racuni layar biru hingga fajar.",
    visual_concept: "Seseorang duduk termenung di angkringan temaram kolong jembatan Lempuyangan Yogyakarta saat senja gerimis, memandangi uap hangat yang naik perlahan dari cangkir seng loreng.",
    image_prompt: "[SUBJECT] An Indonesian man in his late 20s wearing a simple faded shirt * [ORDINARY INDONESIAN ENVIRONMENT] roadside angkringan stall beneath a concrete flyover in Yogyakarta at dusk * [HUMAN ACTION / EMOTION] sitting quietly on a wooden bench, holding a striped enamel tin cup, watching the steam rise with deep somatic presence * [ONE MEANINGFUL DETAIL] a clean continuous spiral of warm steam curling up from the tea into the cool humid twilight air * [LIGHTING] warm yellow kerosene lamp illuminating the food tray and table against the cool blue exterior twilight * [MATERIAL / TEXTURE] chipped enamel tin mug, rough bench timber, wet asphalt, damp night mist * [COMPOSITION] vertical 9:16 layout, person and cup grounded in lower half, broad calm moody atmosphere in upper half * [STYLE] atmospheric Indonesian street photography, authentic 35mm film grain, rich earth tones * [NEGATIVE CONSTRAINTS] no glowing neural circuits, no floating hormone molecules, no sci-fi cyborg overlays, no text, no watermark",
    source_anchor: "Batin yang gelisah sering kali berakar dari pabrik kimia tubuh yang kacau akibat kurang tidur, paparan cahaya biru gawai, dan ritme biologis yang dirusak.",
    reflection_target: "Pengalaman menyalahkan diri sendiri karena mudah marah atau cemas, padahal tubuh fisiknya sedang kelelahan ekstrem akibat kurang tidur."
  },
  {
    page_number: 32,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Lambung Kosong & Ketajaman Indra",
    subtitle: "Mengapa para leluhur berpuasa saat hendak mengambil keputusan besar dalam hidup.",
    side_a_text: "Saat lambungmu kosong seharian, kenapa kepalamu justru terasa lebih awas dan tajam?",
    visual_concept: "Seseorang duduk bersila di amben bambu samping sawah saat tengah hari, memandang hamparan padi yang menguning dengan tatapan jernih tanpa rasa lapar yang menyiksa.",
    image_prompt: "[SUBJECT] An Indonesian person in simple traditional cotton clothes * [ORDINARY INDONESIAN ENVIRONMENT] bamboo resting gazebo (gubuk) beside expansive rice paddies in rural Java * [HUMAN ACTION / EMOTION] sitting peacefully with hands resting on knees, eyes bright and perceptive, experiencing the deep quiet clarity of intermittent fasting * [ONE MEANINGFUL DETAIL] a single clay pitcher of water resting nearby on the bamboo floorboards * [LIGHTING] bright midday tropical sunlight softened by the thatch roof of the gazebo, gentle contrast * [MATERIAL / TEXTURE] split bamboo poles, woven thatch, golden rice stalks, weathered unpainted wood * [COMPOSITION] vertical 9:16 framing, subject centered in lower portion, open golden field and sky stretching above * [STYLE] serene landscape editorial, natural earthy color grading, fine film grain * [NEGATIVE CONSTRAINTS] no glowing stomach graphics, no digestive x-ray, no floating energy runes, no text",
    source_anchor: "Saat sistem pencernaan diistirahatkan lewat puasa, tubuh mengalihkan energi untuk perbaikan sel otak dan menajamkan radar kepekaan indrawi.",
    reflection_target: "Pengalaman merasakan kejernihan pikiran yang tak biasa ketika menjalani puasa dengan niat yang tenang dan sadar."
  },
  {
    page_number: 33,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Guyuran Air Sumur Dingin di Tengkuk",
    subtitle: "Reset instan sistem saraf simpatik lewat sentuhan air tanah alami.",
    side_a_text: "Segelas air dingin di tengkukmu saat fajar sanggup membubarkan kabut pikiran yang buntu berhari-hari.",
    visual_concept: "Seseorang membasuh tengkuk dan wajahnya dengan air timba sumur tua di pelataran belakang rumah saat fajar, butiran air berkilau di kulit.",
    image_prompt: "[SUBJECT] An Indonesian man in casual shorts leaning over a stone well * [ORDINARY INDONESIAN ENVIRONMENT] backyard well in rural Java surrounded by banana trees at early dawn * [HUMAN ACTION / EMOTION] scooping cool well water from a tin bucket and splashing it onto the back of his neck, head tilted forward, exhaling with intense somatic refreshment * [ONE MEANINGFUL DETAIL] crystalline droplets of fresh well water scattering off his neck and skin against the dark stone well ring * [LIGHTING] cool blue twilight of early dawn, gentle first light touching the wet stone and water droplets * [MATERIAL / TEXTURE] rough mossy well stones, galvanised tin bucket, wet human skin, cold well water * [COMPOSITION] vertical 9:16 layout, figure and well occupying lower two-thirds, serene dawn foliage and sky above * [STYLE] raw tactile lifestyle documentary, naturalistic exposure, rich 35mm grain * [NEGATIVE CONSTRAINTS] no glowing blue cold laser effects, no medical nervous system anatomy diagram, no text",
    source_anchor: "Membasuh tengkuk dengan air dingin merangsang saraf vagus, menurunkan detak jantung yang panik, dan mengaktifkan sistem saraf parasimpatik secara seketika.",
    reflection_target: "Momen ketika membasuh muka atau mandi air dingin di pagi hari mendadak mengembalikan kesegaran batin setelah semalaman cemas."
  },
  {
    page_number: 34,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Ritme Sirkadian & Bangun Sebelum Ayam Berkokok",
    subtitle: "Menyelaraskan detak biologis tubuh dengan perputaran poros bumi.",
    side_a_text: "Leluhurmu bangun sebelum ayam berkokok bukan karena takut terlambat kerja, melainkan menyambut gelombang fajar.",
    visual_concept: "Seseorang melangkah keluar dari pintu kayu rumah limasan saat fajar berkabut, menghirup udara segar pekarangan desa yang sunyi.",
    image_prompt: "[SUBJECT] An Indonesian person standing on the front threshold of an old limasan wooden house * [ORDINARY INDONESIAN ENVIRONMENT] rural village courtyard shrouded in light morning mist at first light * [HUMAN ACTION / EMOTION] standing upright, arms relaxed by sides, inhaling the cool mountain air with wide-open lungs and calm reverence * [ONE MEANINGFUL DETAIL] morning dew shining on the wide banana leaves in the front yard * [LIGHTING] soft lavender and amber hues of first dawn touching the horizon through coconut palms * [MATERIAL / TEXTURE] dark hand-hewn timber doorway, dewy foliage, damp gravel pathway * [COMPOSITION] vertical 9:16 frame, person framed symmetrically in the wooden doorway, tranquil morning sky rising above * [STYLE] peaceful rural visual narrative, cinematic soft contrast, fine film grain * [NEGATIVE CONSTRAINTS] no glowing clock or sun diagrams, no futuristic circadian wheels, no CGI, no text",
    source_anchor: "Bangun sebelum fajar menyinkronkan ritme hormon kortisol dan melatonin secara alami dengan siklus cahaya matahari, memulihkan energi fisik tanpa butuh kafein berlebihan.",
    reflection_target: "Pengalaman bangun pagi-pagi sekali saat udara masih sangat segar dan merasakan betapa tenangnya dunia sebelum kebisingan dimulai."
  },
  {
    page_number: 35,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Napas Diafragma & Menenangkan Alarm Bahaya",
    subtitle: "Mengembalikan napas pendek yang panik ke dasar perut yang kokoh.",
    side_a_text: "Napasmu pendek dan memburu di dada; pantas saja hidupmu terasa seperti dikejar bahaya setiap hari.",
    visual_concept: "Seseorang duduk bersila santai di atas tikar pandan di teras rumah, meletakkan satu telapak tangan di atas pusar sembari menarik napas dalam yang mengembang perlahan.",
    image_prompt: "[SUBJECT] An Indonesian person sitting in relaxed cross-legged posture on a woven pandan mat * [ORDINARY INDONESIAN ENVIRONMENT] breezy shaded veranda of a village home in the afternoon * [HUMAN ACTION / EMOTION] one hand resting gently over the lower abdomen just below the navel, shoulders dropped and relaxed, breathing deeply into the belly * [ONE MEANINGFUL DETAIL] the gentle rise of the cotton shirt over the abdomen indicating a deep, centered diaphragmatic breath * [LIGHTING] soft warm afternoon side light passing through potted ferns * [MATERIAL / TEXTURE] woven pandanus mat, smooth unpainted floorboards, soft textured cotton clothing * [COMPOSITION] vertical 9:16 composition, figure grounded in lower half, peaceful open porch background with clean space above * [STYLE] mindful lifestyle photography, calming earthy palette, delicate analog grain * [NEGATIVE CONSTRAINTS] no glowing blue lungs, no medical arrows showing air flow, no CGI ribs, no text",
    source_anchor: "Napas pendek di dada mengirim sinyal ke amigdala bahwa kamu sedang dalam ancaman bahaya. Memindahkan napas ke dasar diafragma mematikan sinyal bahaya palsu itu.",
    reflection_target: "Pengalaman menyadari bahwa saat merasa tertekan atau panik, tarikan napas tanpa sadar menjadi sangat pendek dan dangkal di dada."
  },
  {
    page_number: 36,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Misteri Sentong Tengah & Tirakat Malam",
    subtitle: "Kamar paling gelap di dalam rumah tempat raga melepaskan seluruh beban visual.",
    side_a_text: "Di ruangan mana di rumahmu kamu sanggup duduk tanpa cahaya selain degup napasmu sendiri?",
    visual_concept: "Seseorang duduk bersila di atas amben sentong tengah rumah limasan kayu jati kuno dalam kegelapan pekat yang menenangkan.",
    image_prompt: "[SUBJECT] Silhouette of an Indonesian person seated calmly in the center of an ancient room * [ORDINARY INDONESIAN ENVIRONMENT] traditional Javanese inner private chamber (sentong tengah) enveloped in deep gloom * [HUMAN ACTION / EMOTION] sitting in still meditative repose, comfortable in absolute silence and visual sensory deprivation * [ONE MEANINGFUL DETAIL] a sliver of faint ambient light escaping under a heavy carved teak door, barely outlining the floor * [LIGHTING] extreme low-key lighting, rich natural deep charcoal shadows with soft edge definition * [MATERIAL / TEXTURE] ancient polished teak panels, woven mat, darkness as a tactile physical medium * [COMPOSITION] vertical 9:16 portrait frame, centered silhouette in lower frame surrounded by vast quiet shadow * [STYLE] minimalist chiaroscuro fine art photography, atmospheric grain, deep velvet blacks * [NEGATIVE CONSTRAINTS] no glowing third eye, no spooky horror effects, no purple fantasy aura, no text",
    source_anchor: "Sentong tengah adalah ruangan tanpa jendela di inti rumah Jawa, dirancang untuk memberi kegelapan mutlak agar kelenjar pineal beristirahat total dan membuka penglihatan batin.",
    reflection_target: "Pengalaman duduk sejenak di kamar yang benar-benar gelap dan merasakan betapa lelahnya mata dan otak kita selama ini terpapar cahaya buatan."
  },
  {
    page_number: 37,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Kenyang Berlebihan & Mengubur Kesepian",
    subtitle: "Ketika makanan beralih fungsi dari bahan bakar menjadi obat penenang sementara.",
    side_a_text: "Pernahkah kamu menyadari, rasa kenyang berlebihan sering kali cuma caramu mengubur kesepian?",
    visual_concept: "Sebuah piring enamel berisi sisa makanan bersahaja di meja makan kayu saat larut malam, seseorang duduk termangu menatap piring dengan perasaan begah yang hampa.",
    image_prompt: "[SUBJECT] An Indonesian person sitting alone at a small kitchen table late at night * [ORDINARY INDONESIAN ENVIRONMENT] modest home kitchen in the quiet hours past midnight * [HUMAN ACTION / EMOTION] resting cheek on one hand, looking at an empty dinner plate with a mix of physical fullness and emotional emptiness * [ONE MEANINGFUL DETAIL] a pair of worn wooden chopsticks resting on an empty ceramic bowl, a half-drunk glass of warm tea beside it * [LIGHTING] solitary warm bulb hanging over the table, illuminating the surface while leaving the room edges in shadow * [MATERIAL / TEXTURE] rustic wooden table, glazed ceramic, textured linoleum floor, soft evening shadows * [COMPOSITION] vertical 9:16 layout, table and plate centered in lower frame, quiet dark kitchen wall above * [STYLE] melancholy intimate domestic realism, muted nostalgic colors, 35mm grain * [NEGATIVE CONSTRAINTS] no cartoon food cravings, no glowing belly illustration, no fast-food ads, no text",
    source_anchor: "Makan berlebihan sering kali bukan panggilan lapar fisik, melainkan upaya bawah sadar mencari lonjakan dopamin untuk meredam kekosongan batin yang enggan dihadapi.",
    reflection_target: "Pengalaman terus-menerus mencari camilan atau makan larut malam bukan karena lapar, melainkan karena sedang bosan, gelisah, atau merasa sepi."
  },
  {
    page_number: 38,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Pahitnya Jamu Rempah & Menghidupkan Api Raga",
    subtitle: "Tanaman bumi Nusantara yang diracik untuk menyalakan metabolisme dan sirkulasi darah.",
    side_a_text: "Rasa pahit jamu rempah di lidahmu bekerja membangkitkan panas tubuh yang sudah lama padam.",
    visual_concept: "Seorang wanita penjual jamu gendong menuangkan cairan temulawak dan jahe hangat dari botol kaca ke dalam mangkuk batok kelapa di pasar pagi.",
    image_prompt: "[SUBJECT] Weathered, caring hands of a traditional Indonesian jamu herbalist pouring herbal medicine * [ORDINARY INDONESIAN ENVIRONMENT] morning traditional market corner in Java * [HUMAN ACTION / EMOTION] pouring rich golden-amber liquid from a recycled glass bottle into a polished coconut shell cup * [ONE MEANINGFUL DETAIL] fresh roots of ginger, turmeric, and dried herbs visible in the woven bamboo carrying basket (tenggok) * [LIGHTING] warm early morning market light catching the translucent golden hue of the herbal drink * [MATERIAL / TEXTURE] polished dark coconut shell, clear liquid stream, woven bamboo, rustic glass bottle * [COMPOSITION] vertical 9:16 close-up framing, hands and cup centered, market background softly blurred above * [STYLE] rich cultural documentary photography, vibrant natural earthy tones, authentic film grain * [NEGATIVE CONSTRAINTS] no glowing medicinal sparkles, no fantasy potion vials, no digital flame in cup, no text",
    source_anchor: "Rempah rimpang Nusantara seperti jahe, temulawak, dan kunyit mengaktifkan panas alami tubuh, melancarkan peredaran darah, dan membuang racun peradangan sel.",
    reflection_target: "Pengalaman merasakan kehangatan yang menjalar ke seluruh tubuh setelah meminum seduhan jahe atau jamu tradisional saat badan meriang."
  },
  {
    page_number: 39,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Kaki Telanjang di Atas Tanah Basah",
    subtitle: "Earthing alami yang menetralkan muatan listrik statis dari tubuh yang kelelahan.",
    side_a_text: "Tanah basah yang kau pijak dengan kaki telanjang sedang menyedot keluar racun keletihan harimu.",
    visual_concept: "Dua kaki telanjang seorang pria menjejak rumput hijau basah berembun dan tanah hitam pekarangan desa di pagi hari, terasa kokoh dan sejuk.",
    image_prompt: "[SUBJECT] Bare feet of an Indonesian person standing firmly on natural earth * [ORDINARY INDONESIAN ENVIRONMENT] lush green grass and damp rich soil of a village garden in early morning * [HUMAN ACTION / EMOTION] standing completely still, toes gently digging into the cool moist dirt, feeling the direct somatic connection to the ground * [ONE MEANINGFUL DETAIL] morning dew glinting on fresh grass blades around the ankles, dark moist earth beneath the arches * [LIGHTING] soft golden morning sunlight raking across the lawn at a low angle * [MATERIAL / TEXTURE] moist black loam, fresh green blades, textured skin of feet, morning droplets * [COMPOSITION] vertical 9:16 low-angle framing, feet anchored firmly in lower third, peaceful sunlit garden rising above * [STYLE] grounded organic lifestyle photography, lush natural palette, tactile 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing green electrical earthing arrows, no magnetic field lines, no sci-fi roots growing from feet, no text",
    source_anchor: "Menjejakkan kaki telanjang ke tanah basah memungkinkan transfer elektron bebas dari bumi ke tubuh, menurunkan peradangan dan meredakan ketegangan listrik statis di saraf.",
    reflection_target: "Pengalaman melepas sepatu dan menginjak rumput basah setelah berhari-hari terkurung di ruangan ber-AC dan lantai keramik keras."
  },
  {
    page_number: 40,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Ketika Tubuh Dipaksa Rebah oleh Demam",
    subtitle: "Demam bukanlah musuh, melainkan kecerdasan tubuh yang sedang membersihkan dirinya.",
    side_a_text: "Ada kepasrahan yang luar biasa tenang saat tubuhmu akhirnya dipaksa rebah oleh demam.",
    visual_concept: "Seseorang berbaring tenang di kasur kapuk bersahaja dengan kain kompres basah di keningnya, menatap langit-langit kayu rumah saat hujan rintik di luar.",
    image_prompt: "[SUBJECT] An Indonesian person lying rested in bed under a soft cotton blanket * [ORDINARY INDONESIAN ENVIRONMENT] quiet bedroom of an old wooden family home during a gentle daytime rain * [HUMAN ACTION / EMOTION] eyes open peacefully, looking upward with quiet surrendered acceptance, resting with a cool folded cloth on the forehead * [ONE MEANINGFUL DETAIL] a white enamel bowl of water and folded hand towel resting on a wooden chair beside the bed * [LIGHTING] soft grey rainy daylight filtering through rain-streaked window panes * [MATERIAL / TEXTURE] traditional kapok mattress, woven cotton blanket, damp cloth, dark wooden ceiling rafters * [COMPOSITION] vertical 9:16 layout, person resting in lower frame, calm rhythmic rain light filling the upper frame * [STYLE] poetic intimate drama photography, restrained exposure, soft grain * [NEGATIVE CONSTRAINTS] no glowing thermometer graphics, no red fever fire visuals, no hospital equipment, no text",
    source_anchor: "Saat tubuhmu demam, sistem imun menaikkan suhu untuk melumpuhkan patogen dan memaksa pikiranmu yang sombong untuk berhenti bekerja dan berserah total.",
    reflection_target: "Momen ketika jatuh sakit dan terpaksa membatalkan semua kesibukan, lalu mendadak menyadari bahwa dunia tetap berjalan baik-baik saja tanpa campur tangan kita."
  },
  {
    page_number: 41,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Kelenjar Pineal & Malam yang Tanpa Cahaya",
    subtitle: "Pusat pengendali ritme batin yang merindukan gelapnya malam sejati.",
    side_a_text: "Kelenjar di dasar tengkorakmu tidak butuh obat mahal; ia cuma butuh kegelapan malam tanpa gangguan layar.",
    visual_concept: "Seseorang menarik tirai kain tebal menutup jendela kamar saat malam tiba, menghalangi lampu jalanan kota untuk menciptakan kegelapan yang utuh.",
    image_prompt: "[SUBJECT] An Indonesian person drawing curtains closed in a bedroom at night * [ORDINARY INDONESIAN ENVIRONMENT] modest home bedroom facing an urban street * [HUMAN ACTION / EMOTION] two hands pulling together heavy dark cotton curtains, shutting out the bright glaring yellow streetlamp outside * [ONE MEANINGFUL DETAIL] the sharp beam of orange streetlamp light narrowing into a thin sliver before disappearing into deep room darkness * [LIGHTING] dramatic contrast between the harsh external street lighting and the sheltering interior shadows * [MATERIAL / TEXTURE] heavy woven cotton curtains, painted timber window frame, deep shadow gradients * [COMPOSITION] vertical 9:16 framing, hands and curtain edge centered, shadowy ceiling above * [STYLE] thoughtful atmospheric cinema still, high dynamic range, fine 35mm grain * [NEGATIVE CONSTRAINTS] no glowing pineal cone in skull, no third eye beams, no futuristic brain holograms, no text",
    source_anchor: "Kelenjar pineal hanya memproduksi hormon melatonin dalam kegelapan mutlak. Polusi cahaya malam hari membingungkan kelenjar ini dan merampas kedalaman tidurmu.",
    reflection_target: "Pengalaman tidur di ruangan yang benar-benar gelap gulita dan merasakan betapa pulas serta segarnya badan saat terbangun keesokan paginya."
  },
  {
    page_number: 42,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Gula Berlebih & Ilusi Bahagia Sesaat",
    subtitle: "Lonjakan energi palsu yang selalu dibayar mahal oleh kelelahan mental setelahnya.",
    side_a_text: "Berapa banyak makanan manis yang kau telan hari ini hanya untuk menyogok otakmu yang kelelahan?",
    visual_concept: "Cangkir kopi yang terlalu manis dan bungkusan camilan olahan di meja kerja yang berantakan saat lembur malam, seseorang memijat pelipisnya yang berdenyut pusing.",
    image_prompt: "[SUBJECT] An Indonesian office worker sitting at a cluttered desk at night * [ORDINARY INDONESIAN ENVIRONMENT] modest workspace with paper stacks and laptop light in a dim room * [HUMAN ACTION / EMOTION] one hand gently massaging the temple, eyes closed in mild fatigue, facing the reality of a late-night sugar crash * [ONE MEANINGFUL DETAIL] an empty glass of overly sweet iced boba or milk coffee with melted ice sitting next to scattered snack wrappers * [LIGHTING] harsh cool light from a computer monitor mixed with warm background room shadow * [MATERIAL / TEXTURE] laminated desk surface, plastic cup, condensation drops, rumpled linen shirt * [COMPOSITION] vertical 9:16 layout, worker and desk in lower two-thirds, quiet dim wall space above * [STYLE] realistic contemporary documentary photography, candid observational tone, subtle grain * [NEGATIVE CONSTRAINTS] no cartoon sugar monsters, no glowing dopamine chemical formulas, no exaggerated melodrama, no text",
    source_anchor: "Konsumsi gula berlebih memicu lonjakan insulin dan dopamin yang cepat, diikuti oleh penurunan drastis yang membuatmu cemas, lesu, dan kehilangan fokus.",
    reflection_target: "Pengalaman merasa sangat lemas dan tidak bertenaga beberapa jam setelah memakan makanan atau minuman manis secara berlebihan."
  },
  {
    page_number: 43,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Keringat di Ladang & Pikiran yang Bersih",
    subtitle: "Kerja fisik bersahaja yang membakar kelebihan energi kecemasan di kepala.",
    side_a_text: "Peluh keringat yang menetes setelah mencangkul tanah terasa jauh lebih menenteramkan daripada seratus keluhan di kasur.",
    visual_concept: "Seorang petani atau pemuda desa beristirahat di bawah pohon peneduh di tepi tegalan, menyeka keringat di keningnya dengan handuk kecil sembari tersenyum lega.",
    image_prompt: "[SUBJECT] An Indonesian man in his late 20s resting after physical field work * [ORDINARY INDONESIAN ENVIRONMENT] under the shade of a leafy tamarind tree beside an agricultural field * [HUMAN ACTION / EMOTION] wiping sweat from his brow with a small worn towel, leaning against the tree trunk with deep, honest physical satisfaction * [ONE MEANINGFUL DETAIL] a traditional hoe (cangkul) with earth-caked blade resting nearby against the fertile soil * [LIGHTING] bright tropical afternoon sunlight filtered through leafy branches, creating dappled golden patches * [MATERIAL / TEXTURE] sun-bronzed skin with glistening sweat beads, rough tree bark, damp soil, coarse cotton cloth * [COMPOSITION] vertical 9:16 portrait composition, worker resting at lower-center, canopy of leaves and sunlight above * [STYLE] celebratory documentary of honest labor, warm sunlit color grading, crisp 35mm grain * [NEGATIVE CONSTRAINTS] no glowing aura of endurance, no fitness app statistics floating, no CGI, no text",
    source_anchor: "Aktivitas fisik nyata membakar kelebihan hormon kortisol dan adrenalin yang menumpuk akibat stres mental, memulihkan keseimbangan neurokimia otak secara alami.",
    reflection_target: "Pengalaman merasakan kelegaan batin yang mendalam dan tidur sangat nyenyak setelah seharian lelah melakukan kerja fisik atau olahraga berat."
  },
  {
    page_number: 44,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Menyelaraskan Detak dengan Irama Alam",
    subtitle: "Berhenti memaksakan kecepatan mesin pada raga yang diciptakan dari sari pati tanah.",
    side_a_text: "Tubuhmu punya irama sendiri; kenapa kamu terus memaksanya menari mengikuti jam kantor yang kejam?",
    visual_concept: "Seseorang duduk di peron stasiun komuter kereta api yang sepi di pinggiran kota saat senja, meletakkan tas kerjanya dan menatap matahari yang terbenam perlahan.",
    image_prompt: "[SUBJECT] An Indonesian commuter sitting alone on a wooden bench on an open-air train station platform * [ORDINARY INDONESIAN ENVIRONMENT] quiet suburban railway station in Java during sunset * [HUMAN ACTION / EMOTION] briefcase placed on the bench beside them, leaning back with open posture, watching the golden twilight horizon beyond the railway tracks * [ONE MEANINGFUL DETAIL] long iron railway tracks gleaming in the last orange rays of the setting sun * [LIGHTING] rich golden and purple sunset light flooding the platform, long tranquil shadows * [MATERIAL / TEXTURE] polished wooden bench, rusted iron rails, warm evening breeze, linen clothing * [COMPOSITION] vertical 9:16 frame, commuter resting at bottom-left, vast radiant sunset sky occupying upper two-thirds * [STYLE] poignant cinematic realism, warm saturated tones, analog film grain * [NEGATIVE CONSTRAINTS] no ticking clocks flying in sky, no corporate stress graphs, no surreal vortex, no text",
    source_anchor: "Raga biologismu mengikuti siklus musim dan cahaya matahari. Saat kamu menuntutnya berproduksi konstan tanpa jeda layaknya mesin pabrik, raga akan mengirimkan tagihannya lewat penyakit.",
    reflection_target: "Pengalaman merasa bersalah saat beristirahat santai hanya karena terbiasa dengan tuntutan produktivitas yang tiada habisnya."
  },
  {
    page_number: 45,
    chapter_code: "BAB 03",
    chapter_name: "Sistem Hormon, Biohacking Leluhur & Energi Fisik",
    title: "Menjadi Tuan di Rumah Diri Sendiri",
    subtitle: "Kedaulatan sejati dimulai saat kamu mampu mengendalikan apa yang masuk dan keluar dari ragamu.",
    side_a_text: "Kuasai ragamu maka kau menguasai takdirmu; jadilah tuan yang berdaulat di rumahmu sendiri.",
    visual_concept: "Seseorang berdiri tegak dan tenang dengan kaki telanjang menjejak pasir vulkanik lereng Gunung Merapi saat pagi benderang, angin gunung menerpa bajunya.",
    image_prompt: "[SUBJECT] An Indonesian person in simple traditional linen clothes standing tall, grounded, and centered * [ORDINARY INDONESIAN ENVIRONMENT] volcanic landscape on the slopes of Mount Merapi in clear early morning * [HUMAN ACTION / EMOTION] standing upright with hands relaxed at sides, barefoot on volcanic soil, gazing at the distant misty horizon with quiet self-mastery * [ONE MEANINGFUL DETAIL] fresh hardy green wild grass sprouting tenaciously from the dark fertile volcanic ash around their feet * [LIGHTING] clear, crisp high-altitude morning sunlight, clean sharp shadows * [MATERIAL / TEXTURE] dark volcanic sand, weathered stone, coarse unbleached linen, cool mountain air * [COMPOSITION] vertical 9:16 layout, person standing firmly in lower half, majestic open mountain sky rising above * [STYLE] epic yet restrained documentary photography, crisp organic detail, 35mm film grain * [NEGATIVE CONSTRAINTS] no glowing superhero energy shields, no divine light beams, no mythical beings in clouds, no CGI, no text",
    source_anchor: "Siapa yang tidak mampu mengendalikan apa yang ia suapkan ke mulutnya, berapa jam ia tidur, dan bagaimana ia bernapas, ia tidak akan pernah mampu menjadi pemimpin atas nasib hidupnya.",
    reflection_target: "Momen ketika berhasil menata ulang pola tidur, makanan, dan kebiasaan harian, lalu merasakan kendali hidup kembali berada di tangan sendiri."
  }
];
